/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.resources.batchprocessorrun;

import ai.extend.core.ClientOptions;
import ai.extend.core.RequestOptions;
import ai.extend.resources.batchprocessorrun.types.BatchProcessorRunGetResponse;
import java.util.concurrent.CompletableFuture;

public class AsyncBatchProcessorRunClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawBatchProcessorRunClient rawClient;

    public AsyncBatchProcessorRunClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawBatchProcessorRunClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawBatchProcessorRunClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve details about a batch processor run, including evaluation runs.
     * <p><strong>Deprecated:</strong> This endpoint is maintained for backwards compatibility only and will be replaced in a future API version. Use <a href="/2026-02-09/developers/api-reference/endpoints/evaluation/get-evaluation-set-run">Get Evaluation Set Run</a> for interacting with evaluation set runs.</p>
     */
    public CompletableFuture<BatchProcessorRunGetResponse> get(String id) {
        return this.rawClient.get(id).thenApply(response -> response.body());
    }

    /**
     * Retrieve details about a batch processor run, including evaluation runs.
     * <p><strong>Deprecated:</strong> This endpoint is maintained for backwards compatibility only and will be replaced in a future API version. Use <a href="/2026-02-09/developers/api-reference/endpoints/evaluation/get-evaluation-set-run">Get Evaluation Set Run</a> for interacting with evaluation set runs.</p>
     */
    public CompletableFuture<BatchProcessorRunGetResponse> get(String id, RequestOptions requestOptions) {
        return this.rawClient.get(id, requestOptions).thenApply(response -> response.body());
    }
}
