/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.resources.evaluationsetitem.requests;

import ai.extend.core.ObjectMappers;
import ai.extend.types.SortByEnum;
import ai.extend.types.SortDirEnum;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EvaluationSetItemListRequest.Builder.class)
public final class EvaluationSetItemListRequest {
    private final Optional<String> extendWorkspaceId;

    private final Optional<SortByEnum> sortBy;

    private final Optional<SortDirEnum> sortDir;

    private final Optional<String> nextPageToken;

    private final Optional<Integer> maxPageSize;

    private final Map<String, Object> additionalProperties;

    private EvaluationSetItemListRequest(
            Optional<String> extendWorkspaceId,
            Optional<SortByEnum> sortBy,
            Optional<SortDirEnum> sortDir,
            Optional<String> nextPageToken,
            Optional<Integer> maxPageSize,
            Map<String, Object> additionalProperties) {
        this.extendWorkspaceId = extendWorkspaceId;
        this.sortBy = sortBy;
        this.sortDir = sortDir;
        this.nextPageToken = nextPageToken;
        this.maxPageSize = maxPageSize;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The workspace ID to target. <strong>Required</strong> when using an organization-scoped API key; optional for workspace-scoped keys (the key is already tied to a workspace). See <a href="https://docs.extend.ai/2025-04-21/developers/authentication">Authentication</a> for details on API key scopes.
     */
    @JsonProperty("x-extend-workspace-id")
    public Optional<String> getExtendWorkspaceId() {
        return extendWorkspaceId;
    }

    /**
     * @return Sorts the evaluation set items by the given field.
     */
    @JsonProperty("sortBy")
    public Optional<SortByEnum> getSortBy() {
        return sortBy;
    }

    /**
     * @return Sorts the evaluation set items in ascending or descending order. Ascending order means the earliest evaluation set is returned first.
     */
    @JsonProperty("sortDir")
    public Optional<SortDirEnum> getSortDir() {
        return sortDir;
    }

    @JsonProperty("nextPageToken")
    public Optional<String> getNextPageToken() {
        return nextPageToken;
    }

    @JsonProperty("maxPageSize")
    public Optional<Integer> getMaxPageSize() {
        return maxPageSize;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EvaluationSetItemListRequest && equalTo((EvaluationSetItemListRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EvaluationSetItemListRequest other) {
        return extendWorkspaceId.equals(other.extendWorkspaceId)
                && sortBy.equals(other.sortBy)
                && sortDir.equals(other.sortDir)
                && nextPageToken.equals(other.nextPageToken)
                && maxPageSize.equals(other.maxPageSize);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.extendWorkspaceId, this.sortBy, this.sortDir, this.nextPageToken, this.maxPageSize);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> extendWorkspaceId = Optional.empty();

        private Optional<SortByEnum> sortBy = Optional.empty();

        private Optional<SortDirEnum> sortDir = Optional.empty();

        private Optional<String> nextPageToken = Optional.empty();

        private Optional<Integer> maxPageSize = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(EvaluationSetItemListRequest other) {
            extendWorkspaceId(other.getExtendWorkspaceId());
            sortBy(other.getSortBy());
            sortDir(other.getSortDir());
            nextPageToken(other.getNextPageToken());
            maxPageSize(other.getMaxPageSize());
            return this;
        }

        /**
         * <p>The workspace ID to target. <strong>Required</strong> when using an organization-scoped API key; optional for workspace-scoped keys (the key is already tied to a workspace). See <a href="https://docs.extend.ai/2025-04-21/developers/authentication">Authentication</a> for details on API key scopes.</p>
         */
        @JsonSetter(value = "x-extend-workspace-id", nulls = Nulls.SKIP)
        public Builder extendWorkspaceId(Optional<String> extendWorkspaceId) {
            this.extendWorkspaceId = extendWorkspaceId;
            return this;
        }

        public Builder extendWorkspaceId(String extendWorkspaceId) {
            this.extendWorkspaceId = Optional.ofNullable(extendWorkspaceId);
            return this;
        }

        /**
         * <p>Sorts the evaluation set items by the given field.</p>
         */
        @JsonSetter(value = "sortBy", nulls = Nulls.SKIP)
        public Builder sortBy(Optional<SortByEnum> sortBy) {
            this.sortBy = sortBy;
            return this;
        }

        public Builder sortBy(SortByEnum sortBy) {
            this.sortBy = Optional.ofNullable(sortBy);
            return this;
        }

        /**
         * <p>Sorts the evaluation set items in ascending or descending order. Ascending order means the earliest evaluation set is returned first.</p>
         */
        @JsonSetter(value = "sortDir", nulls = Nulls.SKIP)
        public Builder sortDir(Optional<SortDirEnum> sortDir) {
            this.sortDir = sortDir;
            return this;
        }

        public Builder sortDir(SortDirEnum sortDir) {
            this.sortDir = Optional.ofNullable(sortDir);
            return this;
        }

        @JsonSetter(value = "nextPageToken", nulls = Nulls.SKIP)
        public Builder nextPageToken(Optional<String> nextPageToken) {
            this.nextPageToken = nextPageToken;
            return this;
        }

        public Builder nextPageToken(String nextPageToken) {
            this.nextPageToken = Optional.ofNullable(nextPageToken);
            return this;
        }

        @JsonSetter(value = "maxPageSize", nulls = Nulls.SKIP)
        public Builder maxPageSize(Optional<Integer> maxPageSize) {
            this.maxPageSize = maxPageSize;
            return this;
        }

        public Builder maxPageSize(Integer maxPageSize) {
            this.maxPageSize = Optional.ofNullable(maxPageSize);
            return this;
        }

        public EvaluationSetItemListRequest build() {
            return new EvaluationSetItemListRequest(
                    extendWorkspaceId, sortBy, sortDir, nextPageToken, maxPageSize, additionalProperties);
        }
    }
}
