/**
 * Custom wrapper code - not auto-generated by Fern.
 */
package ai.extend.wrapper.resources;

import ai.extend.core.ClientOptions;
import ai.extend.resources.parseruns.ParseRunsClient;
import ai.extend.resources.parseruns.requests.ParseRunsCreateRequest;
import ai.extend.resources.parseruns.types.ParseRunsCreateResponse;
import ai.extend.resources.parseruns.types.ParseRunsRetrieveResponse;
import ai.extend.types.ParseRunStatusEnum;
import ai.extend.wrapper.errors.PollingTimeoutError;
import ai.extend.wrapper.utilities.polling.Polling;
import ai.extend.wrapper.utilities.polling.PollingOptions;
import java.util.HashSet;
import java.util.Set;

/**
 * Wrapper for ParseRunsClient that adds polling functionality.
 */
public class ParseRunsWrapper {

    private static final Set<ParseRunStatusEnum> NON_TERMINAL_STATUSES;

    static {
        NON_TERMINAL_STATUSES = new HashSet<ParseRunStatusEnum>();
        NON_TERMINAL_STATUSES.add(ParseRunStatusEnum.PROCESSING);
    }

    private final ParseRunsClient client;

    public ParseRunsWrapper(ClientOptions clientOptions) {
        this.client = new ParseRunsClient(clientOptions);
    }

    /**
     * Package-private constructor for testing with a mock client.
     */
    ParseRunsWrapper(ParseRunsClient client) {
        this.client = client;
    }

    /**
     * Returns the underlying ParseRunsClient for direct API access.
     */
    public ParseRunsClient getClient() {
        return client;
    }

    /**
     * Creates a parse run and polls until it reaches a terminal state.
     *
     * <p>Terminal states: PROCESSED, FAILED</p>
     *
     * @param request The create request
     * @return The final response when a terminal state is reached
     * @throws PollingTimeoutError if polling times out before reaching a terminal state
     */
    public ParseRunsRetrieveResponse createAndPoll(ParseRunsCreateRequest request) throws PollingTimeoutError {
        return createAndPoll(request, PollingOptions.defaults());
    }

    /**
     * Creates a parse run and polls until it reaches a terminal state.
     *
     * <p>Terminal states: PROCESSED, FAILED</p>
     *
     * @param request The create request
     * @param options Polling options
     * @return The final response when a terminal state is reached
     * @throws PollingTimeoutError if polling times out before reaching a terminal state
     */
    public ParseRunsRetrieveResponse createAndPoll(ParseRunsCreateRequest request, PollingOptions options)
            throws PollingTimeoutError {

        // Create the parse run
        ParseRunsCreateResponse createResponse = client.create(request);
        final String runId = createResponse.getParseRun().getId();

        // Poll until terminal state
        // Note: ParseRunsClient.retrieve() does not take RequestOptions directly
        return Polling.pollUntilDone(
                () -> client.retrieve(runId),
                response -> isTerminalStatus(response.getParseRun().getStatus()),
                options);
    }

    private boolean isTerminalStatus(ParseRunStatusEnum status) {
        return !NON_TERMINAL_STATUSES.contains(status);
    }
}
