/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class BatchRunStatus {
    public static final BatchRunStatus PROCESSING = new BatchRunStatus(Value.PROCESSING, "PROCESSING");

    public static final BatchRunStatus PROCESSED = new BatchRunStatus(Value.PROCESSED, "PROCESSED");

    public static final BatchRunStatus PENDING = new BatchRunStatus(Value.PENDING, "PENDING");

    public static final BatchRunStatus FAILED = new BatchRunStatus(Value.FAILED, "FAILED");

    private final Value value;

    private final String string;

    BatchRunStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof BatchRunStatus && this.string.equals(((BatchRunStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case PROCESSING:
                return visitor.visitProcessing();
            case PROCESSED:
                return visitor.visitProcessed();
            case PENDING:
                return visitor.visitPending();
            case FAILED:
                return visitor.visitFailed();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static BatchRunStatus valueOf(String value) {
        switch (value) {
            case "PROCESSING":
                return PROCESSING;
            case "PROCESSED":
                return PROCESSED;
            case "PENDING":
                return PENDING;
            case "FAILED":
                return FAILED;
            default:
                return new BatchRunStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        PENDING,

        PROCESSING,

        PROCESSED,

        FAILED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitPending();

        T visitProcessing();

        T visitProcessed();

        T visitFailed();

        T visitUnknown(String unknownType);
    }
}
