/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ChunkType {
    PAGE("page"),

    DOCUMENT("document"),

    SECTION("section");

    private final String value;

    ChunkType(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
