/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.types;

import ai.extend.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ClassifyConfig.Builder.class)
public final class ClassifyConfig {
    private final Optional<ClassifyConfigBaseProcessor> baseProcessor;

    private final Optional<String> baseVersion;

    private final List<Classification> classifications;

    private final Optional<String> classificationRules;

    private final Optional<ClassifyAdvancedOptions> advancedOptions;

    private final Optional<ParseConfig> parseConfig;

    private final Map<String, Object> additionalProperties;

    private ClassifyConfig(
            Optional<ClassifyConfigBaseProcessor> baseProcessor,
            Optional<String> baseVersion,
            List<Classification> classifications,
            Optional<String> classificationRules,
            Optional<ClassifyAdvancedOptions> advancedOptions,
            Optional<ParseConfig> parseConfig,
            Map<String, Object> additionalProperties) {
        this.baseProcessor = baseProcessor;
        this.baseVersion = baseVersion;
        this.classifications = classifications;
        this.classificationRules = classificationRules;
        this.advancedOptions = advancedOptions;
        this.parseConfig = parseConfig;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The base processor to use. For classifiers, this can be either <code>&quot;classification_performance&quot;</code> or <code>&quot;classification_light&quot;</code>. Defaults to <code>&quot;classification_performance&quot;</code> if not provided. See <a href="https://docs.extend.ai/2026-02-09/changelog/classification/classification-performance">Classification Changelog</a> for more details.
     */
    @JsonProperty("baseProcessor")
    public Optional<ClassifyConfigBaseProcessor> getBaseProcessor() {
        return baseProcessor;
    }

    /**
     * @return The version of the <code>&quot;classification_performance&quot;</code> or <code>&quot;classification_light&quot;</code> processor to use. If not provided, the latest stable version for the selected <code>baseProcessor</code> will be used automatically. See <a href="https://docs.extend.ai/2026-02-09/changelog/classification/classification-performance">Classification Changelog</a> for more details.
     */
    @JsonProperty("baseVersion")
    public Optional<String> getBaseVersion() {
        return baseVersion;
    }

    @JsonProperty("classifications")
    public List<Classification> getClassifications() {
        return classifications;
    }

    /**
     * @return Custom rules to guide the classification process in natural language.
     */
    @JsonProperty("classificationRules")
    public Optional<String> getClassificationRules() {
        return classificationRules;
    }

    /**
     * @return Advanced configuration options.
     */
    @JsonProperty("advancedOptions")
    public Optional<ClassifyAdvancedOptions> getAdvancedOptions() {
        return advancedOptions;
    }

    /**
     * @return Configuration options for the parsing process.
     */
    @JsonProperty("parseConfig")
    public Optional<ParseConfig> getParseConfig() {
        return parseConfig;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ClassifyConfig && equalTo((ClassifyConfig) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ClassifyConfig other) {
        return baseProcessor.equals(other.baseProcessor)
                && baseVersion.equals(other.baseVersion)
                && classifications.equals(other.classifications)
                && classificationRules.equals(other.classificationRules)
                && advancedOptions.equals(other.advancedOptions)
                && parseConfig.equals(other.parseConfig);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.baseProcessor,
                this.baseVersion,
                this.classifications,
                this.classificationRules,
                this.advancedOptions,
                this.parseConfig);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<ClassifyConfigBaseProcessor> baseProcessor = Optional.empty();

        private Optional<String> baseVersion = Optional.empty();

        private List<Classification> classifications = new ArrayList<>();

        private Optional<String> classificationRules = Optional.empty();

        private Optional<ClassifyAdvancedOptions> advancedOptions = Optional.empty();

        private Optional<ParseConfig> parseConfig = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ClassifyConfig other) {
            baseProcessor(other.getBaseProcessor());
            baseVersion(other.getBaseVersion());
            classifications(other.getClassifications());
            classificationRules(other.getClassificationRules());
            advancedOptions(other.getAdvancedOptions());
            parseConfig(other.getParseConfig());
            return this;
        }

        /**
         * <p>The base processor to use. For classifiers, this can be either <code>&quot;classification_performance&quot;</code> or <code>&quot;classification_light&quot;</code>. Defaults to <code>&quot;classification_performance&quot;</code> if not provided. See <a href="https://docs.extend.ai/2026-02-09/changelog/classification/classification-performance">Classification Changelog</a> for more details.</p>
         */
        @JsonSetter(value = "baseProcessor", nulls = Nulls.SKIP)
        public Builder baseProcessor(Optional<ClassifyConfigBaseProcessor> baseProcessor) {
            this.baseProcessor = baseProcessor;
            return this;
        }

        public Builder baseProcessor(ClassifyConfigBaseProcessor baseProcessor) {
            this.baseProcessor = Optional.ofNullable(baseProcessor);
            return this;
        }

        /**
         * <p>The version of the <code>&quot;classification_performance&quot;</code> or <code>&quot;classification_light&quot;</code> processor to use. If not provided, the latest stable version for the selected <code>baseProcessor</code> will be used automatically. See <a href="https://docs.extend.ai/2026-02-09/changelog/classification/classification-performance">Classification Changelog</a> for more details.</p>
         */
        @JsonSetter(value = "baseVersion", nulls = Nulls.SKIP)
        public Builder baseVersion(Optional<String> baseVersion) {
            this.baseVersion = baseVersion;
            return this;
        }

        public Builder baseVersion(String baseVersion) {
            this.baseVersion = Optional.ofNullable(baseVersion);
            return this;
        }

        @JsonSetter(value = "classifications", nulls = Nulls.SKIP)
        public Builder classifications(List<Classification> classifications) {
            this.classifications.clear();
            if (classifications != null) {
                this.classifications.addAll(classifications);
            }
            return this;
        }

        public Builder addClassifications(Classification classifications) {
            this.classifications.add(classifications);
            return this;
        }

        public Builder addAllClassifications(List<Classification> classifications) {
            if (classifications != null) {
                this.classifications.addAll(classifications);
            }
            return this;
        }

        /**
         * <p>Custom rules to guide the classification process in natural language.</p>
         */
        @JsonSetter(value = "classificationRules", nulls = Nulls.SKIP)
        public Builder classificationRules(Optional<String> classificationRules) {
            this.classificationRules = classificationRules;
            return this;
        }

        public Builder classificationRules(String classificationRules) {
            this.classificationRules = Optional.ofNullable(classificationRules);
            return this;
        }

        /**
         * <p>Advanced configuration options.</p>
         */
        @JsonSetter(value = "advancedOptions", nulls = Nulls.SKIP)
        public Builder advancedOptions(Optional<ClassifyAdvancedOptions> advancedOptions) {
            this.advancedOptions = advancedOptions;
            return this;
        }

        public Builder advancedOptions(ClassifyAdvancedOptions advancedOptions) {
            this.advancedOptions = Optional.ofNullable(advancedOptions);
            return this;
        }

        /**
         * <p>Configuration options for the parsing process.</p>
         */
        @JsonSetter(value = "parseConfig", nulls = Nulls.SKIP)
        public Builder parseConfig(Optional<ParseConfig> parseConfig) {
            this.parseConfig = parseConfig;
            return this;
        }

        public Builder parseConfig(ParseConfig parseConfig) {
            this.parseConfig = Optional.ofNullable(parseConfig);
            return this;
        }

        public ClassifyConfig build() {
            return new ClassifyConfig(
                    baseProcessor,
                    baseVersion,
                    classifications,
                    classificationRules,
                    advancedOptions,
                    parseConfig,
                    additionalProperties);
        }
    }
}
