/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.types;

import ai.extend.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ConditionalNextEntry.Builder.class)
public final class ConditionalNextEntry {
    private final String step;

    private final String conditionId;

    private final Map<String, Object> additionalProperties;

    private ConditionalNextEntry(String step, String conditionId, Map<String, Object> additionalProperties) {
        this.step = step;
        this.conditionId = conditionId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The name of the target step.
     */
    @JsonProperty("step")
    public String getStep() {
        return step;
    }

    /**
     * @return Must match one of the <code>config.conditions[].id</code> values on the conditional step.
     */
    @JsonProperty("conditionId")
    public String getConditionId() {
        return conditionId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ConditionalNextEntry && equalTo((ConditionalNextEntry) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ConditionalNextEntry other) {
        return step.equals(other.step) && conditionId.equals(other.conditionId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.step, this.conditionId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static StepStage builder() {
        return new Builder();
    }

    public interface StepStage {
        /**
         * <p>The name of the target step.</p>
         */
        ConditionIdStage step(@NotNull String step);

        Builder from(ConditionalNextEntry other);
    }

    public interface ConditionIdStage {
        /**
         * <p>Must match one of the <code>config.conditions[].id</code> values on the conditional step.</p>
         */
        _FinalStage conditionId(@NotNull String conditionId);
    }

    public interface _FinalStage {
        ConditionalNextEntry build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements StepStage, ConditionIdStage, _FinalStage {
        private String step;

        private String conditionId;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ConditionalNextEntry other) {
            step(other.getStep());
            conditionId(other.getConditionId());
            return this;
        }

        /**
         * <p>The name of the target step.</p>
         * <p>The name of the target step.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("step")
        public ConditionIdStage step(@NotNull String step) {
            this.step = Objects.requireNonNull(step, "step must not be null");
            return this;
        }

        /**
         * <p>Must match one of the <code>config.conditions[].id</code> values on the conditional step.</p>
         * <p>Must match one of the <code>config.conditions[].id</code> values on the conditional step.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("conditionId")
        public _FinalStage conditionId(@NotNull String conditionId) {
            this.conditionId = Objects.requireNonNull(conditionId, "conditionId must not be null");
            return this;
        }

        @java.lang.Override
        public ConditionalNextEntry build() {
            return new ConditionalNextEntry(step, conditionId, additionalProperties);
        }
    }
}
