/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.types;

import ai.extend.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EditRunOutputEditedFile.Builder.class)
public final class EditRunOutputEditedFile {
    private final String id;

    private final String presignedUrl;

    private final Map<String, Object> additionalProperties;

    private EditRunOutputEditedFile(String id, String presignedUrl, Map<String, Object> additionalProperties) {
        this.id = id;
        this.presignedUrl = presignedUrl;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The ID of the edited output file.
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return A presigned URL to download the edited file. Expires after 15 minutes.
     */
    @JsonProperty("presignedUrl")
    public String getPresignedUrl() {
        return presignedUrl;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EditRunOutputEditedFile && equalTo((EditRunOutputEditedFile) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EditRunOutputEditedFile other) {
        return id.equals(other.id) && presignedUrl.equals(other.presignedUrl);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.presignedUrl);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>The ID of the edited output file.</p>
         */
        PresignedUrlStage id(@NotNull String id);

        Builder from(EditRunOutputEditedFile other);
    }

    public interface PresignedUrlStage {
        /**
         * <p>A presigned URL to download the edited file. Expires after 15 minutes.</p>
         */
        _FinalStage presignedUrl(@NotNull String presignedUrl);
    }

    public interface _FinalStage {
        EditRunOutputEditedFile build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdStage, PresignedUrlStage, _FinalStage {
        private String id;

        private String presignedUrl;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(EditRunOutputEditedFile other) {
            id(other.getId());
            presignedUrl(other.getPresignedUrl());
            return this;
        }

        /**
         * <p>The ID of the edited output file.</p>
         * <p>The ID of the edited output file.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public PresignedUrlStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>A presigned URL to download the edited file. Expires after 15 minutes.</p>
         * <p>A presigned URL to download the edited file. Expires after 15 minutes.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("presignedUrl")
        public _FinalStage presignedUrl(@NotNull String presignedUrl) {
            this.presignedUrl = Objects.requireNonNull(presignedUrl, "presignedUrl must not be null");
            return this;
        }

        @java.lang.Override
        public EditRunOutputEditedFile build() {
            return new EditRunOutputEditedFile(id, presignedUrl, additionalProperties);
        }
    }
}
