/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.types;

import ai.extend.core.Nullable;
import ai.extend.core.NullableNonemptyFilter;
import ai.extend.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EditTemplate.Builder.class)
public final class EditTemplate {
    private final String id;

    private final String name;

    private final Optional<String> description;

    private final FileSummary file;

    private final EditConfig config;

    private final Optional<EditSchemaGenerationConfig> schemaConfig;

    private final OffsetDateTime createdAt;

    private final OffsetDateTime updatedAt;

    private final Map<String, Object> additionalProperties;

    private EditTemplate(
            String id,
            String name,
            Optional<String> description,
            FileSummary file,
            EditConfig config,
            Optional<EditSchemaGenerationConfig> schemaConfig,
            OffsetDateTime createdAt,
            OffsetDateTime updatedAt,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.file = file;
        this.config = config;
        this.schemaConfig = schemaConfig;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The type of object. Will always be <code>&quot;edit_template&quot;</code>.
     */
    @JsonProperty("object")
    public String getObject() {
        return "edit_template";
    }

    /**
     * @return A unique identifier for the edit template.
     * <p>Example: <code>&quot;edt_xK9mLPqRtN3vS8wF5hB2cQ&quot;</code></p>
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return The name of the edit template.
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return The description of the edit template, if one was provided.
     */
    @JsonIgnore
    public Optional<String> getDescription() {
        if (description == null) {
            return Optional.empty();
        }
        return description;
    }

    /**
     * @return The source file associated with this edit template.
     */
    @JsonProperty("file")
    public FileSummary getFile() {
        return file;
    }

    /**
     * @return Default edit configuration saved on the template. Empty when no edit configuration was saved.
     */
    @JsonProperty("config")
    public EditConfig getConfig() {
        return config;
    }

    /**
     * @return Optional schema generation configuration saved on the template.
     */
    @JsonIgnore
    public Optional<EditSchemaGenerationConfig> getSchemaConfig() {
        if (schemaConfig == null) {
            return Optional.empty();
        }
        return schemaConfig;
    }

    @JsonProperty("createdAt")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    @JsonProperty("updatedAt")
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("description")
    private Optional<String> _getDescription() {
        return description;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("schemaConfig")
    private Optional<EditSchemaGenerationConfig> _getSchemaConfig() {
        return schemaConfig;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EditTemplate && equalTo((EditTemplate) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EditTemplate other) {
        return id.equals(other.id)
                && name.equals(other.name)
                && description.equals(other.description)
                && file.equals(other.file)
                && config.equals(other.config)
                && schemaConfig.equals(other.schemaConfig)
                && createdAt.equals(other.createdAt)
                && updatedAt.equals(other.updatedAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.id,
                this.name,
                this.description,
                this.file,
                this.config,
                this.schemaConfig,
                this.createdAt,
                this.updatedAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>A unique identifier for the edit template.</p>
         * <p>Example: <code>&quot;edt_xK9mLPqRtN3vS8wF5hB2cQ&quot;</code></p>
         */
        NameStage id(@NotNull String id);

        Builder from(EditTemplate other);
    }

    public interface NameStage {
        /**
         * <p>The name of the edit template.</p>
         */
        FileStage name(@NotNull String name);
    }

    public interface FileStage {
        /**
         * <p>The source file associated with this edit template.</p>
         */
        ConfigStage file(@NotNull FileSummary file);
    }

    public interface ConfigStage {
        /**
         * <p>Default edit configuration saved on the template. Empty when no edit configuration was saved.</p>
         */
        CreatedAtStage config(@NotNull EditConfig config);
    }

    public interface CreatedAtStage {
        UpdatedAtStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface UpdatedAtStage {
        _FinalStage updatedAt(@NotNull OffsetDateTime updatedAt);
    }

    public interface _FinalStage {
        EditTemplate build();

        /**
         * <p>The description of the edit template, if one was provided.</p>
         */
        _FinalStage description(Optional<String> description);

        _FinalStage description(String description);

        _FinalStage description(Nullable<String> description);

        /**
         * <p>Optional schema generation configuration saved on the template.</p>
         */
        _FinalStage schemaConfig(Optional<EditSchemaGenerationConfig> schemaConfig);

        _FinalStage schemaConfig(EditSchemaGenerationConfig schemaConfig);

        _FinalStage schemaConfig(Nullable<EditSchemaGenerationConfig> schemaConfig);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IdStage, NameStage, FileStage, ConfigStage, CreatedAtStage, UpdatedAtStage, _FinalStage {
        private String id;

        private String name;

        private FileSummary file;

        private EditConfig config;

        private OffsetDateTime createdAt;

        private OffsetDateTime updatedAt;

        private Optional<EditSchemaGenerationConfig> schemaConfig = Optional.empty();

        private Optional<String> description = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(EditTemplate other) {
            id(other.getId());
            name(other.getName());
            description(other.getDescription());
            file(other.getFile());
            config(other.getConfig());
            schemaConfig(other.getSchemaConfig());
            createdAt(other.getCreatedAt());
            updatedAt(other.getUpdatedAt());
            return this;
        }

        /**
         * <p>A unique identifier for the edit template.</p>
         * <p>Example: <code>&quot;edt_xK9mLPqRtN3vS8wF5hB2cQ&quot;</code></p>
         * <p>A unique identifier for the edit template.</p>
         * <p>Example: <code>&quot;edt_xK9mLPqRtN3vS8wF5hB2cQ&quot;</code></p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public NameStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>The name of the edit template.</p>
         * <p>The name of the edit template.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public FileStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>The source file associated with this edit template.</p>
         * <p>The source file associated with this edit template.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("file")
        public ConfigStage file(@NotNull FileSummary file) {
            this.file = Objects.requireNonNull(file, "file must not be null");
            return this;
        }

        /**
         * <p>Default edit configuration saved on the template. Empty when no edit configuration was saved.</p>
         * <p>Default edit configuration saved on the template. Empty when no edit configuration was saved.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("config")
        public CreatedAtStage config(@NotNull EditConfig config) {
            this.config = Objects.requireNonNull(config, "config must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("createdAt")
        public UpdatedAtStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("updatedAt")
        public _FinalStage updatedAt(@NotNull OffsetDateTime updatedAt) {
            this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
            return this;
        }

        /**
         * <p>Optional schema generation configuration saved on the template.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage schemaConfig(Nullable<EditSchemaGenerationConfig> schemaConfig) {
            if (schemaConfig.isNull()) {
                this.schemaConfig = null;
            } else if (schemaConfig.isEmpty()) {
                this.schemaConfig = Optional.empty();
            } else {
                this.schemaConfig = Optional.of(schemaConfig.get());
            }
            return this;
        }

        /**
         * <p>Optional schema generation configuration saved on the template.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage schemaConfig(EditSchemaGenerationConfig schemaConfig) {
            this.schemaConfig = Optional.ofNullable(schemaConfig);
            return this;
        }

        /**
         * <p>Optional schema generation configuration saved on the template.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "schemaConfig", nulls = Nulls.SKIP)
        public _FinalStage schemaConfig(Optional<EditSchemaGenerationConfig> schemaConfig) {
            this.schemaConfig = schemaConfig;
            return this;
        }

        /**
         * <p>The description of the edit template, if one was provided.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage description(Nullable<String> description) {
            if (description.isNull()) {
                this.description = null;
            } else if (description.isEmpty()) {
                this.description = Optional.empty();
            } else {
                this.description = Optional.of(description.get());
            }
            return this;
        }

        /**
         * <p>The description of the edit template, if one was provided.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage description(String description) {
            this.description = Optional.ofNullable(description);
            return this;
        }

        /**
         * <p>The description of the edit template, if one was provided.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "description", nulls = Nulls.SKIP)
        public _FinalStage description(Optional<String> description) {
            this.description = description;
            return this;
        }

        @java.lang.Override
        public EditTemplate build() {
            return new EditTemplate(
                    id, name, description, file, config, schemaConfig, createdAt, updatedAt, additionalProperties);
        }
    }
}
