/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.types;

import ai.extend.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EditSchemaGenerationResponse.Builder.class)
public final class EditSchemaGenerationResponse {
    private final EditRootJsonSchema schema;

    private final Optional<EditRootJsonSchema> annotatedSchema;

    private final Optional<EditSchemaGenerationMappingResult> mappingResult;

    private final Map<String, Object> additionalProperties;

    private EditSchemaGenerationResponse(
            EditRootJsonSchema schema,
            Optional<EditRootJsonSchema> annotatedSchema,
            Optional<EditSchemaGenerationMappingResult> mappingResult,
            Map<String, Object> additionalProperties) {
        this.schema = schema;
        this.annotatedSchema = annotatedSchema;
        this.mappingResult = mappingResult;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The final generated schema after mapping. If no input schema was provided this will be the same as the annotatedSchema.
     */
    @JsonProperty("schema")
    public EditRootJsonSchema getSchema() {
        return schema;
    }

    /**
     * @return The original schema that was detected and annotated from the file.
     */
    @JsonProperty("annotatedSchema")
    public Optional<EditRootJsonSchema> getAnnotatedSchema() {
        return annotatedSchema;
    }

    /**
     * @return Mapping information between <code>inputSchema</code> paths and detected form fields when an input schema was provided.
     */
    @JsonProperty("mappingResult")
    public Optional<EditSchemaGenerationMappingResult> getMappingResult() {
        return mappingResult;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EditSchemaGenerationResponse && equalTo((EditSchemaGenerationResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EditSchemaGenerationResponse other) {
        return schema.equals(other.schema)
                && annotatedSchema.equals(other.annotatedSchema)
                && mappingResult.equals(other.mappingResult);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.schema, this.annotatedSchema, this.mappingResult);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static SchemaStage builder() {
        return new Builder();
    }

    public interface SchemaStage {
        /**
         * <p>The final generated schema after mapping. If no input schema was provided this will be the same as the annotatedSchema.</p>
         */
        _FinalStage schema(@NotNull EditRootJsonSchema schema);

        Builder from(EditSchemaGenerationResponse other);
    }

    public interface _FinalStage {
        EditSchemaGenerationResponse build();

        /**
         * <p>The original schema that was detected and annotated from the file.</p>
         */
        _FinalStage annotatedSchema(Optional<EditRootJsonSchema> annotatedSchema);

        _FinalStage annotatedSchema(EditRootJsonSchema annotatedSchema);

        /**
         * <p>Mapping information between <code>inputSchema</code> paths and detected form fields when an input schema was provided.</p>
         */
        _FinalStage mappingResult(Optional<EditSchemaGenerationMappingResult> mappingResult);

        _FinalStage mappingResult(EditSchemaGenerationMappingResult mappingResult);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements SchemaStage, _FinalStage {
        private EditRootJsonSchema schema;

        private Optional<EditSchemaGenerationMappingResult> mappingResult = Optional.empty();

        private Optional<EditRootJsonSchema> annotatedSchema = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(EditSchemaGenerationResponse other) {
            schema(other.getSchema());
            annotatedSchema(other.getAnnotatedSchema());
            mappingResult(other.getMappingResult());
            return this;
        }

        /**
         * <p>The final generated schema after mapping. If no input schema was provided this will be the same as the annotatedSchema.</p>
         * <p>The final generated schema after mapping. If no input schema was provided this will be the same as the annotatedSchema.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("schema")
        public _FinalStage schema(@NotNull EditRootJsonSchema schema) {
            this.schema = Objects.requireNonNull(schema, "schema must not be null");
            return this;
        }

        /**
         * <p>Mapping information between <code>inputSchema</code> paths and detected form fields when an input schema was provided.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage mappingResult(EditSchemaGenerationMappingResult mappingResult) {
            this.mappingResult = Optional.ofNullable(mappingResult);
            return this;
        }

        /**
         * <p>Mapping information between <code>inputSchema</code> paths and detected form fields when an input schema was provided.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "mappingResult", nulls = Nulls.SKIP)
        public _FinalStage mappingResult(Optional<EditSchemaGenerationMappingResult> mappingResult) {
            this.mappingResult = mappingResult;
            return this;
        }

        /**
         * <p>The original schema that was detected and annotated from the file.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage annotatedSchema(EditRootJsonSchema annotatedSchema) {
            this.annotatedSchema = Optional.ofNullable(annotatedSchema);
            return this;
        }

        /**
         * <p>The original schema that was detected and annotated from the file.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "annotatedSchema", nulls = Nulls.SKIP)
        public _FinalStage annotatedSchema(Optional<EditRootJsonSchema> annotatedSchema) {
            this.annotatedSchema = annotatedSchema;
            return this;
        }

        @java.lang.Override
        public EditSchemaGenerationResponse build() {
            return new EditSchemaGenerationResponse(schema, annotatedSchema, mappingResult, additionalProperties);
        }
    }
}
