/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.types;

import ai.extend.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EditRunMetrics.Builder.class)
public final class EditRunMetrics {
    private final double processingTimeMs;

    private final int pageCount;

    private final int fieldCount;

    private final int fieldsDetectedCount;

    private final int fieldsAnnotatedCount;

    private final double fieldDetectionTimeMs;

    private final double fieldAnnotationTimeMs;

    private final double fieldFillingTimeMs;

    private final Map<String, Object> additionalProperties;

    private EditRunMetrics(
            double processingTimeMs,
            int pageCount,
            int fieldCount,
            int fieldsDetectedCount,
            int fieldsAnnotatedCount,
            double fieldDetectionTimeMs,
            double fieldAnnotationTimeMs,
            double fieldFillingTimeMs,
            Map<String, Object> additionalProperties) {
        this.processingTimeMs = processingTimeMs;
        this.pageCount = pageCount;
        this.fieldCount = fieldCount;
        this.fieldsDetectedCount = fieldsDetectedCount;
        this.fieldsAnnotatedCount = fieldsAnnotatedCount;
        this.fieldDetectionTimeMs = fieldDetectionTimeMs;
        this.fieldAnnotationTimeMs = fieldAnnotationTimeMs;
        this.fieldFillingTimeMs = fieldFillingTimeMs;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Total processing time in milliseconds.
     */
    @JsonProperty("processingTimeMs")
    public double getProcessingTimeMs() {
        return processingTimeMs;
    }

    /**
     * @return The number of pages in the document.
     */
    @JsonProperty("pageCount")
    public int getPageCount() {
        return pageCount;
    }

    /**
     * @return The total number of fields in the schema.
     */
    @JsonProperty("fieldCount")
    public int getFieldCount() {
        return fieldCount;
    }

    /**
     * @return The number of fields that were automatically detected.
     */
    @JsonProperty("fieldsDetectedCount")
    public int getFieldsDetectedCount() {
        return fieldsDetectedCount;
    }

    /**
     * @return The number of fields that were annotated with bounding boxes.
     */
    @JsonProperty("fieldsAnnotatedCount")
    public int getFieldsAnnotatedCount() {
        return fieldsAnnotatedCount;
    }

    /**
     * @return The time taken to detect fields in the document, in milliseconds.
     */
    @JsonProperty("fieldDetectionTimeMs")
    public double getFieldDetectionTimeMs() {
        return fieldDetectionTimeMs;
    }

    /**
     * @return The time taken to annotate field positions in the document, in milliseconds.
     */
    @JsonProperty("fieldAnnotationTimeMs")
    public double getFieldAnnotationTimeMs() {
        return fieldAnnotationTimeMs;
    }

    /**
     * @return The time taken to fill the fields in the document, in milliseconds.
     */
    @JsonProperty("fieldFillingTimeMs")
    public double getFieldFillingTimeMs() {
        return fieldFillingTimeMs;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EditRunMetrics && equalTo((EditRunMetrics) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EditRunMetrics other) {
        return processingTimeMs == other.processingTimeMs
                && pageCount == other.pageCount
                && fieldCount == other.fieldCount
                && fieldsDetectedCount == other.fieldsDetectedCount
                && fieldsAnnotatedCount == other.fieldsAnnotatedCount
                && fieldDetectionTimeMs == other.fieldDetectionTimeMs
                && fieldAnnotationTimeMs == other.fieldAnnotationTimeMs
                && fieldFillingTimeMs == other.fieldFillingTimeMs;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.processingTimeMs,
                this.pageCount,
                this.fieldCount,
                this.fieldsDetectedCount,
                this.fieldsAnnotatedCount,
                this.fieldDetectionTimeMs,
                this.fieldAnnotationTimeMs,
                this.fieldFillingTimeMs);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ProcessingTimeMsStage builder() {
        return new Builder();
    }

    public interface ProcessingTimeMsStage {
        /**
         * <p>Total processing time in milliseconds.</p>
         */
        PageCountStage processingTimeMs(double processingTimeMs);

        Builder from(EditRunMetrics other);
    }

    public interface PageCountStage {
        /**
         * <p>The number of pages in the document.</p>
         */
        FieldCountStage pageCount(int pageCount);
    }

    public interface FieldCountStage {
        /**
         * <p>The total number of fields in the schema.</p>
         */
        FieldsDetectedCountStage fieldCount(int fieldCount);
    }

    public interface FieldsDetectedCountStage {
        /**
         * <p>The number of fields that were automatically detected.</p>
         */
        FieldsAnnotatedCountStage fieldsDetectedCount(int fieldsDetectedCount);
    }

    public interface FieldsAnnotatedCountStage {
        /**
         * <p>The number of fields that were annotated with bounding boxes.</p>
         */
        FieldDetectionTimeMsStage fieldsAnnotatedCount(int fieldsAnnotatedCount);
    }

    public interface FieldDetectionTimeMsStage {
        /**
         * <p>The time taken to detect fields in the document, in milliseconds.</p>
         */
        FieldAnnotationTimeMsStage fieldDetectionTimeMs(double fieldDetectionTimeMs);
    }

    public interface FieldAnnotationTimeMsStage {
        /**
         * <p>The time taken to annotate field positions in the document, in milliseconds.</p>
         */
        FieldFillingTimeMsStage fieldAnnotationTimeMs(double fieldAnnotationTimeMs);
    }

    public interface FieldFillingTimeMsStage {
        /**
         * <p>The time taken to fill the fields in the document, in milliseconds.</p>
         */
        _FinalStage fieldFillingTimeMs(double fieldFillingTimeMs);
    }

    public interface _FinalStage {
        EditRunMetrics build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements ProcessingTimeMsStage,
                    PageCountStage,
                    FieldCountStage,
                    FieldsDetectedCountStage,
                    FieldsAnnotatedCountStage,
                    FieldDetectionTimeMsStage,
                    FieldAnnotationTimeMsStage,
                    FieldFillingTimeMsStage,
                    _FinalStage {
        private double processingTimeMs;

        private int pageCount;

        private int fieldCount;

        private int fieldsDetectedCount;

        private int fieldsAnnotatedCount;

        private double fieldDetectionTimeMs;

        private double fieldAnnotationTimeMs;

        private double fieldFillingTimeMs;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(EditRunMetrics other) {
            processingTimeMs(other.getProcessingTimeMs());
            pageCount(other.getPageCount());
            fieldCount(other.getFieldCount());
            fieldsDetectedCount(other.getFieldsDetectedCount());
            fieldsAnnotatedCount(other.getFieldsAnnotatedCount());
            fieldDetectionTimeMs(other.getFieldDetectionTimeMs());
            fieldAnnotationTimeMs(other.getFieldAnnotationTimeMs());
            fieldFillingTimeMs(other.getFieldFillingTimeMs());
            return this;
        }

        /**
         * <p>Total processing time in milliseconds.</p>
         * <p>Total processing time in milliseconds.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("processingTimeMs")
        public PageCountStage processingTimeMs(double processingTimeMs) {
            this.processingTimeMs = processingTimeMs;
            return this;
        }

        /**
         * <p>The number of pages in the document.</p>
         * <p>The number of pages in the document.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("pageCount")
        public FieldCountStage pageCount(int pageCount) {
            this.pageCount = pageCount;
            return this;
        }

        /**
         * <p>The total number of fields in the schema.</p>
         * <p>The total number of fields in the schema.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("fieldCount")
        public FieldsDetectedCountStage fieldCount(int fieldCount) {
            this.fieldCount = fieldCount;
            return this;
        }

        /**
         * <p>The number of fields that were automatically detected.</p>
         * <p>The number of fields that were automatically detected.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("fieldsDetectedCount")
        public FieldsAnnotatedCountStage fieldsDetectedCount(int fieldsDetectedCount) {
            this.fieldsDetectedCount = fieldsDetectedCount;
            return this;
        }

        /**
         * <p>The number of fields that were annotated with bounding boxes.</p>
         * <p>The number of fields that were annotated with bounding boxes.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("fieldsAnnotatedCount")
        public FieldDetectionTimeMsStage fieldsAnnotatedCount(int fieldsAnnotatedCount) {
            this.fieldsAnnotatedCount = fieldsAnnotatedCount;
            return this;
        }

        /**
         * <p>The time taken to detect fields in the document, in milliseconds.</p>
         * <p>The time taken to detect fields in the document, in milliseconds.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("fieldDetectionTimeMs")
        public FieldAnnotationTimeMsStage fieldDetectionTimeMs(double fieldDetectionTimeMs) {
            this.fieldDetectionTimeMs = fieldDetectionTimeMs;
            return this;
        }

        /**
         * <p>The time taken to annotate field positions in the document, in milliseconds.</p>
         * <p>The time taken to annotate field positions in the document, in milliseconds.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("fieldAnnotationTimeMs")
        public FieldFillingTimeMsStage fieldAnnotationTimeMs(double fieldAnnotationTimeMs) {
            this.fieldAnnotationTimeMs = fieldAnnotationTimeMs;
            return this;
        }

        /**
         * <p>The time taken to fill the fields in the document, in milliseconds.</p>
         * <p>The time taken to fill the fields in the document, in milliseconds.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("fieldFillingTimeMs")
        public _FinalStage fieldFillingTimeMs(double fieldFillingTimeMs) {
            this.fieldFillingTimeMs = fieldFillingTimeMs;
            return this;
        }

        @java.lang.Override
        public EditRunMetrics build() {
            return new EditRunMetrics(
                    processingTimeMs,
                    pageCount,
                    fieldCount,
                    fieldsDetectedCount,
                    fieldsAnnotatedCount,
                    fieldDetectionTimeMs,
                    fieldAnnotationTimeMs,
                    fieldFillingTimeMs,
                    additionalProperties);
        }
    }
}
