/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.types;

import ai.extend.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EvaluationSet.Builder.class)
public final class EvaluationSet {
    private final String id;

    private final String name;

    private final String description;

    private final EvaluationSetEntity entity;

    private final OffsetDateTime createdAt;

    private final OffsetDateTime updatedAt;

    private final Map<String, Object> additionalProperties;

    private EvaluationSet(
            String id,
            String name,
            String description,
            EvaluationSetEntity entity,
            OffsetDateTime createdAt,
            OffsetDateTime updatedAt,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.entity = entity;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The type of object. In this case, it will always be <code>&quot;evaluation_set&quot;</code>.
     */
    @JsonProperty("object")
    public String getObject() {
        return "evaluation_set";
    }

    /**
     * @return The ID of the evaluation set.
     * <p>Example: <code>&quot;ev_2LcgeY_mp2T5yPaEuq5Lw&quot;</code></p>
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return The name of the evaluation set.
     * <p>Example: <code>&quot;Invoice Processing Test Set&quot;</code></p>
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return A description of the evaluation set.
     * <p>Example: <code>&quot;Q4 2023 vendor invoices for accuracy testing&quot;</code></p>
     */
    @JsonProperty("description")
    public String getDescription() {
        return description;
    }

    /**
     * @return The extractor, classifier, or splitter associated with this evaluation set.
     */
    @JsonProperty("entity")
    public EvaluationSetEntity getEntity() {
        return entity;
    }

    @JsonProperty("createdAt")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    @JsonProperty("updatedAt")
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EvaluationSet && equalTo((EvaluationSet) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EvaluationSet other) {
        return id.equals(other.id)
                && name.equals(other.name)
                && description.equals(other.description)
                && entity.equals(other.entity)
                && createdAt.equals(other.createdAt)
                && updatedAt.equals(other.updatedAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.name, this.description, this.entity, this.createdAt, this.updatedAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>The ID of the evaluation set.</p>
         * <p>Example: <code>&quot;ev_2LcgeY_mp2T5yPaEuq5Lw&quot;</code></p>
         */
        NameStage id(@NotNull String id);

        Builder from(EvaluationSet other);
    }

    public interface NameStage {
        /**
         * <p>The name of the evaluation set.</p>
         * <p>Example: <code>&quot;Invoice Processing Test Set&quot;</code></p>
         */
        DescriptionStage name(@NotNull String name);
    }

    public interface DescriptionStage {
        /**
         * <p>A description of the evaluation set.</p>
         * <p>Example: <code>&quot;Q4 2023 vendor invoices for accuracy testing&quot;</code></p>
         */
        EntityStage description(@NotNull String description);
    }

    public interface EntityStage {
        /**
         * <p>The extractor, classifier, or splitter associated with this evaluation set.</p>
         */
        CreatedAtStage entity(@NotNull EvaluationSetEntity entity);
    }

    public interface CreatedAtStage {
        UpdatedAtStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface UpdatedAtStage {
        _FinalStage updatedAt(@NotNull OffsetDateTime updatedAt);
    }

    public interface _FinalStage {
        EvaluationSet build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IdStage, NameStage, DescriptionStage, EntityStage, CreatedAtStage, UpdatedAtStage, _FinalStage {
        private String id;

        private String name;

        private String description;

        private EvaluationSetEntity entity;

        private OffsetDateTime createdAt;

        private OffsetDateTime updatedAt;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(EvaluationSet other) {
            id(other.getId());
            name(other.getName());
            description(other.getDescription());
            entity(other.getEntity());
            createdAt(other.getCreatedAt());
            updatedAt(other.getUpdatedAt());
            return this;
        }

        /**
         * <p>The ID of the evaluation set.</p>
         * <p>Example: <code>&quot;ev_2LcgeY_mp2T5yPaEuq5Lw&quot;</code></p>
         * <p>The ID of the evaluation set.</p>
         * <p>Example: <code>&quot;ev_2LcgeY_mp2T5yPaEuq5Lw&quot;</code></p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public NameStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>The name of the evaluation set.</p>
         * <p>Example: <code>&quot;Invoice Processing Test Set&quot;</code></p>
         * <p>The name of the evaluation set.</p>
         * <p>Example: <code>&quot;Invoice Processing Test Set&quot;</code></p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public DescriptionStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>A description of the evaluation set.</p>
         * <p>Example: <code>&quot;Q4 2023 vendor invoices for accuracy testing&quot;</code></p>
         * <p>A description of the evaluation set.</p>
         * <p>Example: <code>&quot;Q4 2023 vendor invoices for accuracy testing&quot;</code></p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("description")
        public EntityStage description(@NotNull String description) {
            this.description = Objects.requireNonNull(description, "description must not be null");
            return this;
        }

        /**
         * <p>The extractor, classifier, or splitter associated with this evaluation set.</p>
         * <p>The extractor, classifier, or splitter associated with this evaluation set.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("entity")
        public CreatedAtStage entity(@NotNull EvaluationSetEntity entity) {
            this.entity = Objects.requireNonNull(entity, "entity must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("createdAt")
        public UpdatedAtStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("updatedAt")
        public _FinalStage updatedAt(@NotNull OffsetDateTime updatedAt) {
            this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
            return this;
        }

        @java.lang.Override
        public EvaluationSet build() {
            return new EvaluationSet(id, name, description, entity, createdAt, updatedAt, additionalProperties);
        }
    }
}
