/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ExternalDataValidationStepDefinitionConfigRequestOptionsContentType {
    public static final ExternalDataValidationStepDefinitionConfigRequestOptionsContentType TEXT_PLAIN =
            new ExternalDataValidationStepDefinitionConfigRequestOptionsContentType(Value.TEXT_PLAIN, "text/plain");

    public static final ExternalDataValidationStepDefinitionConfigRequestOptionsContentType APPLICATION_JSON =
            new ExternalDataValidationStepDefinitionConfigRequestOptionsContentType(
                    Value.APPLICATION_JSON, "application/json");

    private final Value value;

    private final String string;

    ExternalDataValidationStepDefinitionConfigRequestOptionsContentType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ExternalDataValidationStepDefinitionConfigRequestOptionsContentType
                        && this.string.equals(
                                ((ExternalDataValidationStepDefinitionConfigRequestOptionsContentType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case TEXT_PLAIN:
                return visitor.visitTextPlain();
            case APPLICATION_JSON:
                return visitor.visitApplicationJson();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ExternalDataValidationStepDefinitionConfigRequestOptionsContentType valueOf(String value) {
        switch (value) {
            case "text/plain":
                return TEXT_PLAIN;
            case "application/json":
                return APPLICATION_JSON;
            default:
                return new ExternalDataValidationStepDefinitionConfigRequestOptionsContentType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        APPLICATION_JSON,

        TEXT_PLAIN,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitApplicationJson();

        T visitTextPlain();

        T visitUnknown(String unknownType);
    }
}
