/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ExtractAdvancedOptionsArrayCitationStrategy {
    public static final ExtractAdvancedOptionsArrayCitationStrategy PROPERTY =
            new ExtractAdvancedOptionsArrayCitationStrategy(Value.PROPERTY, "property");

    public static final ExtractAdvancedOptionsArrayCitationStrategy ITEM =
            new ExtractAdvancedOptionsArrayCitationStrategy(Value.ITEM, "item");

    private final Value value;

    private final String string;

    ExtractAdvancedOptionsArrayCitationStrategy(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ExtractAdvancedOptionsArrayCitationStrategy
                        && this.string.equals(((ExtractAdvancedOptionsArrayCitationStrategy) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case PROPERTY:
                return visitor.visitProperty();
            case ITEM:
                return visitor.visitItem();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ExtractAdvancedOptionsArrayCitationStrategy valueOf(String value) {
        switch (value) {
            case "property":
                return PROPERTY;
            case "item":
                return ITEM;
            default:
                return new ExtractAdvancedOptionsArrayCitationStrategy(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ITEM,

        PROPERTY,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitItem();

        T visitProperty();

        T visitUnknown(String unknownType);
    }
}
