/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.types;

import ai.extend.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ExtractConfigLegacy.Builder.class)
public final class ExtractConfigLegacy {
    private final Optional<ExtractConfigLegacyBaseProcessor> baseProcessor;

    private final Optional<String> baseVersion;

    private final Optional<String> extractionRules;

    private final List<ExtractionField> fields;

    private final Optional<ExtractAdvancedOptions> advancedOptions;

    private final Optional<ParseConfig> parseConfig;

    private final Map<String, Object> additionalProperties;

    private ExtractConfigLegacy(
            Optional<ExtractConfigLegacyBaseProcessor> baseProcessor,
            Optional<String> baseVersion,
            Optional<String> extractionRules,
            List<ExtractionField> fields,
            Optional<ExtractAdvancedOptions> advancedOptions,
            Optional<ParseConfig> parseConfig,
            Map<String, Object> additionalProperties) {
        this.baseProcessor = baseProcessor;
        this.baseVersion = baseVersion;
        this.extractionRules = extractionRules;
        this.fields = fields;
        this.advancedOptions = advancedOptions;
        this.parseConfig = parseConfig;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The base processor to use. For extractors, this can be either <code>&quot;extraction_performance&quot;</code> or <code>&quot;extraction_light&quot;</code>. Defaults to <code>&quot;extraction_performance&quot;</code> if not provided. See <a href="https://docs.extend.ai/2026-02-09/changelog/extraction/extraction-performance">Extraction Changelog</a> for more details.
     */
    @JsonProperty("baseProcessor")
    public Optional<ExtractConfigLegacyBaseProcessor> getBaseProcessor() {
        return baseProcessor;
    }

    /**
     * @return The version of the <code>&quot;extraction_performance&quot;</code> or <code>&quot;extraction_light&quot;</code> processor to use. If not provided, the latest stable version for the selected <code>baseProcessor</code> will be used automatically. See <a href="https://docs.extend.ai/2026-02-09/changelog/extraction/extraction-performance">Extraction Changelog</a> for more details.
     */
    @JsonProperty("baseVersion")
    public Optional<String> getBaseVersion() {
        return baseVersion;
    }

    /**
     * @return Custom rules to guide the extraction process in natural language.
     */
    @JsonProperty("extractionRules")
    public Optional<String> getExtractionRules() {
        return extractionRules;
    }

    /**
     * @return Array of fields to extract from the document. This is the legacy format.
     * <p>We recommend using JSON Schema (<code>schema</code> property) for new implementations.</p>
     */
    @JsonProperty("fields")
    public List<ExtractionField> getFields() {
        return fields;
    }

    /**
     * @return Advanced configuration options.
     */
    @JsonProperty("advancedOptions")
    public Optional<ExtractAdvancedOptions> getAdvancedOptions() {
        return advancedOptions;
    }

    /**
     * @return Configuration options for the parsing process.
     */
    @JsonProperty("parseConfig")
    public Optional<ParseConfig> getParseConfig() {
        return parseConfig;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ExtractConfigLegacy && equalTo((ExtractConfigLegacy) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ExtractConfigLegacy other) {
        return baseProcessor.equals(other.baseProcessor)
                && baseVersion.equals(other.baseVersion)
                && extractionRules.equals(other.extractionRules)
                && fields.equals(other.fields)
                && advancedOptions.equals(other.advancedOptions)
                && parseConfig.equals(other.parseConfig);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.baseProcessor,
                this.baseVersion,
                this.extractionRules,
                this.fields,
                this.advancedOptions,
                this.parseConfig);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<ExtractConfigLegacyBaseProcessor> baseProcessor = Optional.empty();

        private Optional<String> baseVersion = Optional.empty();

        private Optional<String> extractionRules = Optional.empty();

        private List<ExtractionField> fields = new ArrayList<>();

        private Optional<ExtractAdvancedOptions> advancedOptions = Optional.empty();

        private Optional<ParseConfig> parseConfig = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ExtractConfigLegacy other) {
            baseProcessor(other.getBaseProcessor());
            baseVersion(other.getBaseVersion());
            extractionRules(other.getExtractionRules());
            fields(other.getFields());
            advancedOptions(other.getAdvancedOptions());
            parseConfig(other.getParseConfig());
            return this;
        }

        /**
         * <p>The base processor to use. For extractors, this can be either <code>&quot;extraction_performance&quot;</code> or <code>&quot;extraction_light&quot;</code>. Defaults to <code>&quot;extraction_performance&quot;</code> if not provided. See <a href="https://docs.extend.ai/2026-02-09/changelog/extraction/extraction-performance">Extraction Changelog</a> for more details.</p>
         */
        @JsonSetter(value = "baseProcessor", nulls = Nulls.SKIP)
        public Builder baseProcessor(Optional<ExtractConfigLegacyBaseProcessor> baseProcessor) {
            this.baseProcessor = baseProcessor;
            return this;
        }

        public Builder baseProcessor(ExtractConfigLegacyBaseProcessor baseProcessor) {
            this.baseProcessor = Optional.ofNullable(baseProcessor);
            return this;
        }

        /**
         * <p>The version of the <code>&quot;extraction_performance&quot;</code> or <code>&quot;extraction_light&quot;</code> processor to use. If not provided, the latest stable version for the selected <code>baseProcessor</code> will be used automatically. See <a href="https://docs.extend.ai/2026-02-09/changelog/extraction/extraction-performance">Extraction Changelog</a> for more details.</p>
         */
        @JsonSetter(value = "baseVersion", nulls = Nulls.SKIP)
        public Builder baseVersion(Optional<String> baseVersion) {
            this.baseVersion = baseVersion;
            return this;
        }

        public Builder baseVersion(String baseVersion) {
            this.baseVersion = Optional.ofNullable(baseVersion);
            return this;
        }

        /**
         * <p>Custom rules to guide the extraction process in natural language.</p>
         */
        @JsonSetter(value = "extractionRules", nulls = Nulls.SKIP)
        public Builder extractionRules(Optional<String> extractionRules) {
            this.extractionRules = extractionRules;
            return this;
        }

        public Builder extractionRules(String extractionRules) {
            this.extractionRules = Optional.ofNullable(extractionRules);
            return this;
        }

        /**
         * <p>Array of fields to extract from the document. This is the legacy format.</p>
         * <p>We recommend using JSON Schema (<code>schema</code> property) for new implementations.</p>
         */
        @JsonSetter(value = "fields", nulls = Nulls.SKIP)
        public Builder fields(List<ExtractionField> fields) {
            this.fields.clear();
            if (fields != null) {
                this.fields.addAll(fields);
            }
            return this;
        }

        public Builder addFields(ExtractionField fields) {
            this.fields.add(fields);
            return this;
        }

        public Builder addAllFields(List<ExtractionField> fields) {
            if (fields != null) {
                this.fields.addAll(fields);
            }
            return this;
        }

        /**
         * <p>Advanced configuration options.</p>
         */
        @JsonSetter(value = "advancedOptions", nulls = Nulls.SKIP)
        public Builder advancedOptions(Optional<ExtractAdvancedOptions> advancedOptions) {
            this.advancedOptions = advancedOptions;
            return this;
        }

        public Builder advancedOptions(ExtractAdvancedOptions advancedOptions) {
            this.advancedOptions = Optional.ofNullable(advancedOptions);
            return this;
        }

        /**
         * <p>Configuration options for the parsing process.</p>
         */
        @JsonSetter(value = "parseConfig", nulls = Nulls.SKIP)
        public Builder parseConfig(Optional<ParseConfig> parseConfig) {
            this.parseConfig = parseConfig;
            return this;
        }

        public Builder parseConfig(ParseConfig parseConfig) {
            this.parseConfig = Optional.ofNullable(parseConfig);
            return this;
        }

        public ExtractConfigLegacy build() {
            return new ExtractConfigLegacy(
                    baseProcessor,
                    baseVersion,
                    extractionRules,
                    fields,
                    advancedOptions,
                    parseConfig,
                    additionalProperties);
        }
    }
}
