/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.types;

import ai.extend.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FileContentsSectionsItem.Builder.class)
public final class FileContentsSectionsItem {
    private final int startPageNumber;

    private final int endPageNumber;

    private final String markdown;

    private final Map<String, Object> additionalProperties;

    private FileContentsSectionsItem(
            int startPageNumber, int endPageNumber, String markdown, Map<String, Object> additionalProperties) {
        this.startPageNumber = startPageNumber;
        this.endPageNumber = endPageNumber;
        this.markdown = markdown;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The starting page number of this section.
     */
    @JsonProperty("startPageNumber")
    public int getStartPageNumber() {
        return startPageNumber;
    }

    /**
     * @return The ending page number of this section.
     */
    @JsonProperty("endPageNumber")
    public int getEndPageNumber() {
        return endPageNumber;
    }

    /**
     * @return The markdown content of this section.
     */
    @JsonProperty("markdown")
    public String getMarkdown() {
        return markdown;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof FileContentsSectionsItem && equalTo((FileContentsSectionsItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(FileContentsSectionsItem other) {
        return startPageNumber == other.startPageNumber
                && endPageNumber == other.endPageNumber
                && markdown.equals(other.markdown);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.startPageNumber, this.endPageNumber, this.markdown);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static StartPageNumberStage builder() {
        return new Builder();
    }

    public interface StartPageNumberStage {
        /**
         * <p>The starting page number of this section.</p>
         */
        EndPageNumberStage startPageNumber(int startPageNumber);

        Builder from(FileContentsSectionsItem other);
    }

    public interface EndPageNumberStage {
        /**
         * <p>The ending page number of this section.</p>
         */
        MarkdownStage endPageNumber(int endPageNumber);
    }

    public interface MarkdownStage {
        /**
         * <p>The markdown content of this section.</p>
         */
        _FinalStage markdown(@NotNull String markdown);
    }

    public interface _FinalStage {
        FileContentsSectionsItem build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements StartPageNumberStage, EndPageNumberStage, MarkdownStage, _FinalStage {
        private int startPageNumber;

        private int endPageNumber;

        private String markdown;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(FileContentsSectionsItem other) {
            startPageNumber(other.getStartPageNumber());
            endPageNumber(other.getEndPageNumber());
            markdown(other.getMarkdown());
            return this;
        }

        /**
         * <p>The starting page number of this section.</p>
         * <p>The starting page number of this section.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("startPageNumber")
        public EndPageNumberStage startPageNumber(int startPageNumber) {
            this.startPageNumber = startPageNumber;
            return this;
        }

        /**
         * <p>The ending page number of this section.</p>
         * <p>The ending page number of this section.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("endPageNumber")
        public MarkdownStage endPageNumber(int endPageNumber) {
            this.endPageNumber = endPageNumber;
            return this;
        }

        /**
         * <p>The markdown content of this section.</p>
         * <p>The markdown content of this section.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("markdown")
        public _FinalStage markdown(@NotNull String markdown) {
            this.markdown = Objects.requireNonNull(markdown, "markdown must not be null");
            return this;
        }

        @java.lang.Override
        public FileContentsSectionsItem build() {
            return new FileContentsSectionsItem(startPageNumber, endPageNumber, markdown, additionalProperties);
        }
    }
}
