/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.types;

import ai.extend.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FileFromUrlSettings.Builder.class)
public final class FileFromUrlSettings {
    private final Optional<String> password;

    private final Map<String, Object> additionalProperties;

    private FileFromUrlSettings(Optional<String> password, Map<String, Object> additionalProperties) {
        this.password = password;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The password to unlock a password-protected PDF.
     */
    @JsonProperty("password")
    public Optional<String> getPassword() {
        return password;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof FileFromUrlSettings && equalTo((FileFromUrlSettings) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(FileFromUrlSettings other) {
        return password.equals(other.password);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.password);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> password = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(FileFromUrlSettings other) {
            password(other.getPassword());
            return this;
        }

        /**
         * <p>The password to unlock a password-protected PDF.</p>
         */
        @JsonSetter(value = "password", nulls = Nulls.SKIP)
        public Builder password(Optional<String> password) {
            this.password = password;
            return this;
        }

        public Builder password(String password) {
            this.password = Optional.ofNullable(password);
            return this;
        }

        public FileFromUrlSettings build() {
            return new FileFromUrlSettings(password, additionalProperties);
        }
    }
}
