/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.types;

import ai.extend.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FormulaDetails.Builder.class)
public final class FormulaDetails {
    private final Optional<String> latex;

    private final Map<String, Object> additionalProperties;

    private FormulaDetails(Optional<String> latex, Map<String, Object> additionalProperties) {
        this.latex = latex;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Indicates this is a formula details object
     */
    @JsonProperty("type")
    public String getType() {
        return "formula_details";
    }

    /**
     * @return The LaTeX representation of the detected formula.
     */
    @JsonProperty("latex")
    public Optional<String> getLatex() {
        return latex;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof FormulaDetails && equalTo((FormulaDetails) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(FormulaDetails other) {
        return latex.equals(other.latex);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.latex);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> latex = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(FormulaDetails other) {
            latex(other.getLatex());
            return this;
        }

        /**
         * <p>The LaTeX representation of the detected formula.</p>
         */
        @JsonSetter(value = "latex", nulls = Nulls.SKIP)
        public Builder latex(Optional<String> latex) {
            this.latex = latex;
            return this;
        }

        public Builder latex(String latex) {
            this.latex = Optional.ofNullable(latex);
            return this;
        }

        public FormulaDetails build() {
            return new FormulaDetails(latex, additionalProperties);
        }
    }
}
