/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class LegacySplitterAdvancedOptionsSplitMethod {
    public static final LegacySplitterAdvancedOptionsSplitMethod HIGH_PRECISION =
            new LegacySplitterAdvancedOptionsSplitMethod(Value.HIGH_PRECISION, "high_precision");

    public static final LegacySplitterAdvancedOptionsSplitMethod LOW_LATENCY =
            new LegacySplitterAdvancedOptionsSplitMethod(Value.LOW_LATENCY, "low_latency");

    private final Value value;

    private final String string;

    LegacySplitterAdvancedOptionsSplitMethod(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof LegacySplitterAdvancedOptionsSplitMethod
                        && this.string.equals(((LegacySplitterAdvancedOptionsSplitMethod) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case HIGH_PRECISION:
                return visitor.visitHighPrecision();
            case LOW_LATENCY:
                return visitor.visitLowLatency();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static LegacySplitterAdvancedOptionsSplitMethod valueOf(String value) {
        switch (value) {
            case "high_precision":
                return HIGH_PRECISION;
            case "low_latency":
                return LOW_LATENCY;
            default:
                return new LegacySplitterAdvancedOptionsSplitMethod(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        HIGH_PRECISION,

        LOW_LATENCY,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitHighPrecision();

        T visitLowLatency();

        T visitUnknown(String unknownType);
    }
}
