/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class LegacyExtractionConfigBaseProcessor {
    public static final LegacyExtractionConfigBaseProcessor EXTRACTION_PERFORMANCE =
            new LegacyExtractionConfigBaseProcessor(Value.EXTRACTION_PERFORMANCE, "extraction_performance");

    public static final LegacyExtractionConfigBaseProcessor EXTRACTION_LIGHT =
            new LegacyExtractionConfigBaseProcessor(Value.EXTRACTION_LIGHT, "extraction_light");

    private final Value value;

    private final String string;

    LegacyExtractionConfigBaseProcessor(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof LegacyExtractionConfigBaseProcessor
                        && this.string.equals(((LegacyExtractionConfigBaseProcessor) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case EXTRACTION_PERFORMANCE:
                return visitor.visitExtractionPerformance();
            case EXTRACTION_LIGHT:
                return visitor.visitExtractionLight();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static LegacyExtractionConfigBaseProcessor valueOf(String value) {
        switch (value) {
            case "extraction_performance":
                return EXTRACTION_PERFORMANCE;
            case "extraction_light":
                return EXTRACTION_LIGHT;
            default:
                return new LegacyExtractionConfigBaseProcessor(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        EXTRACTION_PERFORMANCE,

        EXTRACTION_LIGHT,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitExtractionPerformance();

        T visitExtractionLight();

        T visitUnknown(String unknownType);
    }
}
