/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.types;

import ai.extend.core.Nullable;
import ai.extend.core.NullableNonemptyFilter;
import ai.extend.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = LegacyJsonOutputMetadataValue.Builder.class)
public final class LegacyJsonOutputMetadataValue {
    private final Optional<Double> ocrConfidence;

    private final Optional<Double> logprobsConfidence;

    private final Optional<Integer> reviewAgentScore;

    private final Optional<List<LegacyJsonOutputMetadataValueCitationsItem>> citations;

    private final Optional<List<Insight>> insights;

    private final Map<String, Object> additionalProperties;

    private LegacyJsonOutputMetadataValue(
            Optional<Double> ocrConfidence,
            Optional<Double> logprobsConfidence,
            Optional<Integer> reviewAgentScore,
            Optional<List<LegacyJsonOutputMetadataValueCitationsItem>> citations,
            Optional<List<Insight>> insights,
            Map<String, Object> additionalProperties) {
        this.ocrConfidence = ocrConfidence;
        this.logprobsConfidence = logprobsConfidence;
        this.reviewAgentScore = reviewAgentScore;
        this.citations = citations;
        this.insights = insights;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Confidence score from OCR processing, if applicable
     */
    @JsonIgnore
    public Optional<Double> getOcrConfidence() {
        if (ocrConfidence == null) {
            return Optional.empty();
        }
        return ocrConfidence;
    }

    /**
     * @return Confidence score based on model logprobs
     */
    @JsonIgnore
    public Optional<Double> getLogprobsConfidence() {
        if (logprobsConfidence == null) {
            return Optional.empty();
        }
        return logprobsConfidence;
    }

    /**
     * @return A 1-5 score indicating the review agent's confidence in the extracted value.
     * <ul>
     * <li>5: High confidence, no issues detected</li>
     * <li>4: Good confidence, minor observations</li>
     * <li>3: Moderate confidence, some uncertainty</li>
     * <li>2: Low confidence, likely issues</li>
     * <li>1: Very low confidence, significant problems detected</li>
     * </ul>
     * <p>These scores will be present when the <code>reviewAgent.enabled</code> flag is set to <code>true</code> in the processor config.
     * If the review agent is enabled but a score is not returned for a field, this value will be <code>null</code>.
     * To learn more, view the <a href="https://docs.extend.ai/product/extraction/review-agent">Review Agent Documentation</a></p>
     */
    @JsonIgnore
    public Optional<Integer> getReviewAgentScore() {
        if (reviewAgentScore == null) {
            return Optional.empty();
        }
        return reviewAgentScore;
    }

    @JsonProperty("citations")
    public Optional<List<LegacyJsonOutputMetadataValueCitationsItem>> getCitations() {
        return citations;
    }

    @JsonProperty("insights")
    public Optional<List<Insight>> getInsights() {
        return insights;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("ocrConfidence")
    private Optional<Double> _getOcrConfidence() {
        return ocrConfidence;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("logprobsConfidence")
    private Optional<Double> _getLogprobsConfidence() {
        return logprobsConfidence;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("reviewAgentScore")
    private Optional<Integer> _getReviewAgentScore() {
        return reviewAgentScore;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof LegacyJsonOutputMetadataValue && equalTo((LegacyJsonOutputMetadataValue) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(LegacyJsonOutputMetadataValue other) {
        return ocrConfidence.equals(other.ocrConfidence)
                && logprobsConfidence.equals(other.logprobsConfidence)
                && reviewAgentScore.equals(other.reviewAgentScore)
                && citations.equals(other.citations)
                && insights.equals(other.insights);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.ocrConfidence, this.logprobsConfidence, this.reviewAgentScore, this.citations, this.insights);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Double> ocrConfidence = Optional.empty();

        private Optional<Double> logprobsConfidence = Optional.empty();

        private Optional<Integer> reviewAgentScore = Optional.empty();

        private Optional<List<LegacyJsonOutputMetadataValueCitationsItem>> citations = Optional.empty();

        private Optional<List<Insight>> insights = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(LegacyJsonOutputMetadataValue other) {
            ocrConfidence(other.getOcrConfidence());
            logprobsConfidence(other.getLogprobsConfidence());
            reviewAgentScore(other.getReviewAgentScore());
            citations(other.getCitations());
            insights(other.getInsights());
            return this;
        }

        /**
         * <p>Confidence score from OCR processing, if applicable</p>
         */
        @JsonSetter(value = "ocrConfidence", nulls = Nulls.SKIP)
        public Builder ocrConfidence(Optional<Double> ocrConfidence) {
            this.ocrConfidence = ocrConfidence;
            return this;
        }

        public Builder ocrConfidence(Double ocrConfidence) {
            this.ocrConfidence = Optional.ofNullable(ocrConfidence);
            return this;
        }

        public Builder ocrConfidence(Nullable<Double> ocrConfidence) {
            if (ocrConfidence.isNull()) {
                this.ocrConfidence = null;
            } else if (ocrConfidence.isEmpty()) {
                this.ocrConfidence = Optional.empty();
            } else {
                this.ocrConfidence = Optional.of(ocrConfidence.get());
            }
            return this;
        }

        /**
         * <p>Confidence score based on model logprobs</p>
         */
        @JsonSetter(value = "logprobsConfidence", nulls = Nulls.SKIP)
        public Builder logprobsConfidence(Optional<Double> logprobsConfidence) {
            this.logprobsConfidence = logprobsConfidence;
            return this;
        }

        public Builder logprobsConfidence(Double logprobsConfidence) {
            this.logprobsConfidence = Optional.ofNullable(logprobsConfidence);
            return this;
        }

        public Builder logprobsConfidence(Nullable<Double> logprobsConfidence) {
            if (logprobsConfidence.isNull()) {
                this.logprobsConfidence = null;
            } else if (logprobsConfidence.isEmpty()) {
                this.logprobsConfidence = Optional.empty();
            } else {
                this.logprobsConfidence = Optional.of(logprobsConfidence.get());
            }
            return this;
        }

        /**
         * <p>A 1-5 score indicating the review agent's confidence in the extracted value.</p>
         * <ul>
         * <li>5: High confidence, no issues detected</li>
         * <li>4: Good confidence, minor observations</li>
         * <li>3: Moderate confidence, some uncertainty</li>
         * <li>2: Low confidence, likely issues</li>
         * <li>1: Very low confidence, significant problems detected</li>
         * </ul>
         * <p>These scores will be present when the <code>reviewAgent.enabled</code> flag is set to <code>true</code> in the processor config.
         * If the review agent is enabled but a score is not returned for a field, this value will be <code>null</code>.
         * To learn more, view the <a href="https://docs.extend.ai/product/extraction/review-agent">Review Agent Documentation</a></p>
         */
        @JsonSetter(value = "reviewAgentScore", nulls = Nulls.SKIP)
        public Builder reviewAgentScore(Optional<Integer> reviewAgentScore) {
            this.reviewAgentScore = reviewAgentScore;
            return this;
        }

        public Builder reviewAgentScore(Integer reviewAgentScore) {
            this.reviewAgentScore = Optional.ofNullable(reviewAgentScore);
            return this;
        }

        public Builder reviewAgentScore(Nullable<Integer> reviewAgentScore) {
            if (reviewAgentScore.isNull()) {
                this.reviewAgentScore = null;
            } else if (reviewAgentScore.isEmpty()) {
                this.reviewAgentScore = Optional.empty();
            } else {
                this.reviewAgentScore = Optional.of(reviewAgentScore.get());
            }
            return this;
        }

        @JsonSetter(value = "citations", nulls = Nulls.SKIP)
        public Builder citations(Optional<List<LegacyJsonOutputMetadataValueCitationsItem>> citations) {
            this.citations = citations;
            return this;
        }

        public Builder citations(List<LegacyJsonOutputMetadataValueCitationsItem> citations) {
            this.citations = Optional.ofNullable(citations);
            return this;
        }

        @JsonSetter(value = "insights", nulls = Nulls.SKIP)
        public Builder insights(Optional<List<Insight>> insights) {
            this.insights = insights;
            return this;
        }

        public Builder insights(List<Insight> insights) {
            this.insights = Optional.ofNullable(insights);
            return this;
        }

        public LegacyJsonOutputMetadataValue build() {
            return new LegacyJsonOutputMetadataValue(
                    ocrConfidence, logprobsConfidence, reviewAgentScore, citations, insights, additionalProperties);
        }
    }
}
