/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.types;

import ai.extend.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MergeExtractStepDefinitionConfig.Builder.class)
public final class MergeExtractStepDefinitionConfig {
    private final Optional<MergeExtractStepDefinitionConfigMergeOrder> mergeOrder;

    private final Map<String, Object> additionalProperties;

    private MergeExtractStepDefinitionConfig(
            Optional<MergeExtractStepDefinitionConfigMergeOrder> mergeOrder, Map<String, Object> additionalProperties) {
        this.mergeOrder = mergeOrder;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return How to order fields when merging. Defaults to confidence.
     * <p>See the <a href="https://docs.extend.ai/2026-02-09/product/workflows/configuring-workflows-via-api#merge-extract-step">Merge Extract step docs</a>.</p>
     */
    @JsonProperty("mergeOrder")
    public Optional<MergeExtractStepDefinitionConfigMergeOrder> getMergeOrder() {
        return mergeOrder;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof MergeExtractStepDefinitionConfig && equalTo((MergeExtractStepDefinitionConfig) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(MergeExtractStepDefinitionConfig other) {
        return mergeOrder.equals(other.mergeOrder);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.mergeOrder);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<MergeExtractStepDefinitionConfigMergeOrder> mergeOrder = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(MergeExtractStepDefinitionConfig other) {
            mergeOrder(other.getMergeOrder());
            return this;
        }

        /**
         * <p>How to order fields when merging. Defaults to confidence.</p>
         * <p>See the <a href="https://docs.extend.ai/2026-02-09/product/workflows/configuring-workflows-via-api#merge-extract-step">Merge Extract step docs</a>.</p>
         */
        @JsonSetter(value = "mergeOrder", nulls = Nulls.SKIP)
        public Builder mergeOrder(Optional<MergeExtractStepDefinitionConfigMergeOrder> mergeOrder) {
            this.mergeOrder = mergeOrder;
            return this;
        }

        public Builder mergeOrder(MergeExtractStepDefinitionConfigMergeOrder mergeOrder) {
            this.mergeOrder = Optional.ofNullable(mergeOrder);
            return this;
        }

        public MergeExtractStepDefinitionConfig build() {
            return new MergeExtractStepDefinitionConfig(mergeOrder, additionalProperties);
        }
    }
}
