/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.types;

import ai.extend.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ParseConfigBlockOptionsFigures.Builder.class)
public final class ParseConfigBlockOptionsFigures {
    private final Optional<Boolean> enabled;

    private final Optional<Boolean> figureImageClippingEnabled;

    private final Optional<Boolean> advancedChartExtractionEnabled;

    private final Optional<String> customInstructions;

    private final Map<String, Object> additionalProperties;

    private ParseConfigBlockOptionsFigures(
            Optional<Boolean> enabled,
            Optional<Boolean> figureImageClippingEnabled,
            Optional<Boolean> advancedChartExtractionEnabled,
            Optional<String> customInstructions,
            Map<String, Object> additionalProperties) {
        this.enabled = enabled;
        this.figureImageClippingEnabled = figureImageClippingEnabled;
        this.advancedChartExtractionEnabled = advancedChartExtractionEnabled;
        this.customInstructions = customInstructions;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Whether to include figures in the output.
     */
    @JsonProperty("enabled")
    public Optional<Boolean> getEnabled() {
        return enabled;
    }

    /**
     * @return Whether to clip and extract images from figures.
     */
    @JsonProperty("figureImageClippingEnabled")
    public Optional<Boolean> getFigureImageClippingEnabled() {
        return figureImageClippingEnabled;
    }

    /**
     * @return Whether to enable advanced chart extraction using vision models for improved data extraction from charts.
     */
    @JsonProperty("advancedChartExtractionEnabled")
    public Optional<Boolean> getAdvancedChartExtractionEnabled() {
        return advancedChartExtractionEnabled;
    }

    /**
     * @return Custom instructions injected into the vision model prompt used to analyze and summarize figures. Use to steer figure descriptions toward your use case (e.g. domain terminology, details to always capture). Requires <code>enabled: true</code>. Available on <code>parse_performance</code> &gt;= <code>2.0.0</code> and <code>parse_light</code> &gt;= <code>1.0.0</code>.
     */
    @JsonProperty("customInstructions")
    public Optional<String> getCustomInstructions() {
        return customInstructions;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ParseConfigBlockOptionsFigures && equalTo((ParseConfigBlockOptionsFigures) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ParseConfigBlockOptionsFigures other) {
        return enabled.equals(other.enabled)
                && figureImageClippingEnabled.equals(other.figureImageClippingEnabled)
                && advancedChartExtractionEnabled.equals(other.advancedChartExtractionEnabled)
                && customInstructions.equals(other.customInstructions);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.enabled,
                this.figureImageClippingEnabled,
                this.advancedChartExtractionEnabled,
                this.customInstructions);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Boolean> enabled = Optional.empty();

        private Optional<Boolean> figureImageClippingEnabled = Optional.empty();

        private Optional<Boolean> advancedChartExtractionEnabled = Optional.empty();

        private Optional<String> customInstructions = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ParseConfigBlockOptionsFigures other) {
            enabled(other.getEnabled());
            figureImageClippingEnabled(other.getFigureImageClippingEnabled());
            advancedChartExtractionEnabled(other.getAdvancedChartExtractionEnabled());
            customInstructions(other.getCustomInstructions());
            return this;
        }

        /**
         * <p>Whether to include figures in the output.</p>
         */
        @JsonSetter(value = "enabled", nulls = Nulls.SKIP)
        public Builder enabled(Optional<Boolean> enabled) {
            this.enabled = enabled;
            return this;
        }

        public Builder enabled(Boolean enabled) {
            this.enabled = Optional.ofNullable(enabled);
            return this;
        }

        /**
         * <p>Whether to clip and extract images from figures.</p>
         */
        @JsonSetter(value = "figureImageClippingEnabled", nulls = Nulls.SKIP)
        public Builder figureImageClippingEnabled(Optional<Boolean> figureImageClippingEnabled) {
            this.figureImageClippingEnabled = figureImageClippingEnabled;
            return this;
        }

        public Builder figureImageClippingEnabled(Boolean figureImageClippingEnabled) {
            this.figureImageClippingEnabled = Optional.ofNullable(figureImageClippingEnabled);
            return this;
        }

        /**
         * <p>Whether to enable advanced chart extraction using vision models for improved data extraction from charts.</p>
         */
        @JsonSetter(value = "advancedChartExtractionEnabled", nulls = Nulls.SKIP)
        public Builder advancedChartExtractionEnabled(Optional<Boolean> advancedChartExtractionEnabled) {
            this.advancedChartExtractionEnabled = advancedChartExtractionEnabled;
            return this;
        }

        public Builder advancedChartExtractionEnabled(Boolean advancedChartExtractionEnabled) {
            this.advancedChartExtractionEnabled = Optional.ofNullable(advancedChartExtractionEnabled);
            return this;
        }

        /**
         * <p>Custom instructions injected into the vision model prompt used to analyze and summarize figures. Use to steer figure descriptions toward your use case (e.g. domain terminology, details to always capture). Requires <code>enabled: true</code>. Available on <code>parse_performance</code> &gt;= <code>2.0.0</code> and <code>parse_light</code> &gt;= <code>1.0.0</code>.</p>
         */
        @JsonSetter(value = "customInstructions", nulls = Nulls.SKIP)
        public Builder customInstructions(Optional<String> customInstructions) {
            this.customInstructions = customInstructions;
            return this;
        }

        public Builder customInstructions(String customInstructions) {
            this.customInstructions = Optional.ofNullable(customInstructions);
            return this;
        }

        public ParseConfigBlockOptionsFigures build() {
            return new ParseConfigBlockOptionsFigures(
                    enabled,
                    figureImageClippingEnabled,
                    advancedChartExtractionEnabled,
                    customInstructions,
                    additionalProperties);
        }
    }
}
