/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ProcessorRunStatus {
    PROCESSING("PROCESSING"),

    PROCESSED("PROCESSED"),

    FAILED("FAILED"),

    CANCELLED("CANCELLED");

    private final String value;

    ProcessorRunStatus(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
