/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.types;

import ai.extend.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import java.io.IOException;
import java.util.Map;
import java.util.Objects;

@JsonDeserialize(using = ProvidedExtractionOutput.Deserializer.class)
public final class ProvidedExtractionOutput {
    private final Object value;

    private final int type;

    private ProvidedExtractionOutput(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    @SuppressWarnings("unchecked")
    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((ProvidedJsonOutput) this.value);
        } else if (this.type == 1) {
            return visitor.visit((Map<String, ProvidedExtractionFieldResult>) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ProvidedExtractionOutput && equalTo((ProvidedExtractionOutput) other);
    }

    private boolean equalTo(ProvidedExtractionOutput other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
        return this.value.toString();
    }

    public static ProvidedExtractionOutput of(ProvidedJsonOutput value) {
        return new ProvidedExtractionOutput(value, 0);
    }

    public static ProvidedExtractionOutput of(Map<String, ProvidedExtractionFieldResult> value) {
        return new ProvidedExtractionOutput(value, 1);
    }

    public interface Visitor<T> {
        T visit(ProvidedJsonOutput value);

        T visit(Map<String, ProvidedExtractionFieldResult> value);
    }

    static final class Deserializer extends StdDeserializer<ProvidedExtractionOutput> {
        Deserializer() {
            super(ProvidedExtractionOutput.class);
        }

        @java.lang.Override
        public ProvidedExtractionOutput deserialize(JsonParser p, DeserializationContext context) throws IOException {
            Object value = p.readValueAs(Object.class);
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, ProvidedJsonOutput.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(
                        value, new TypeReference<Map<String, ProvidedExtractionFieldResult>>() {}));
            } catch (RuntimeException e) {
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
