/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum WebhookEventProcessorRunEventType {
    PROCESSOR_RUN_PROCESSED("processor_run.processed"),

    PROCESSOR_RUN_FAILED("processor_run.failed");

    private final String value;

    WebhookEventProcessorRunEventType(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
