/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.types;

import ai.extend.core.Nullable;
import ai.extend.core.NullableNonemptyFilter;
import ai.extend.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = WebhookEndpointCreate.Builder.class)
public final class WebhookEndpointCreate {
    private final String id;

    private final String url;

    private final String name;

    private final WebhookEndpointStatus status;

    private final List<WebhookEndpointEventType> enabledEvents;

    private final ApiVersionEnum apiVersion;

    private final Optional<WebhookAdvancedOptions> advancedOptions;

    private final String signingSecret;

    private final OffsetDateTime createdAt;

    private final Map<String, Object> additionalProperties;

    private WebhookEndpointCreate(
            String id,
            String url,
            String name,
            WebhookEndpointStatus status,
            List<WebhookEndpointEventType> enabledEvents,
            ApiVersionEnum apiVersion,
            Optional<WebhookAdvancedOptions> advancedOptions,
            String signingSecret,
            OffsetDateTime createdAt,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.url = url;
        this.name = name;
        this.status = status;
        this.enabledEvents = enabledEvents;
        this.apiVersion = apiVersion;
        this.advancedOptions = advancedOptions;
        this.signingSecret = signingSecret;
        this.createdAt = createdAt;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("object")
    public String getObject() {
        return "webhook_endpoint";
    }

    /**
     * @return Unique identifier for the webhook endpoint.
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return The URL that webhook events are sent to.
     */
    @JsonProperty("url")
    public String getUrl() {
        return url;
    }

    /**
     * @return A human-readable name for the webhook endpoint.
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    @JsonProperty("status")
    public WebhookEndpointStatus getStatus() {
        return status;
    }

    /**
     * @return The list of event types this endpoint is subscribed to at the global level. These are events that are not scoped to a specific resource.
     */
    @JsonProperty("enabledEvents")
    public List<WebhookEndpointEventType> getEnabledEvents() {
        return enabledEvents;
    }

    @JsonProperty("apiVersion")
    public ApiVersionEnum getApiVersion() {
        return apiVersion;
    }

    /**
     * @return Advanced configuration options for the webhook endpoint, including custom headers and payload delivery settings.
     */
    @JsonIgnore
    public Optional<WebhookAdvancedOptions> getAdvancedOptions() {
        if (advancedOptions == null) {
            return Optional.empty();
        }
        return advancedOptions;
    }

    /**
     * @return The signing secret used to verify webhook payloads. This is only returned when creating the endpoint and cannot be retrieved again.
     * <p>Store it securely — you will need it to verify webhook signatures.</p>
     */
    @JsonProperty("signingSecret")
    public String getSigningSecret() {
        return signingSecret;
    }

    /**
     * @return The date and time the webhook endpoint was created.
     */
    @JsonProperty("createdAt")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("advancedOptions")
    private Optional<WebhookAdvancedOptions> _getAdvancedOptions() {
        return advancedOptions;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof WebhookEndpointCreate && equalTo((WebhookEndpointCreate) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(WebhookEndpointCreate other) {
        return id.equals(other.id)
                && url.equals(other.url)
                && name.equals(other.name)
                && status.equals(other.status)
                && enabledEvents.equals(other.enabledEvents)
                && apiVersion.equals(other.apiVersion)
                && advancedOptions.equals(other.advancedOptions)
                && signingSecret.equals(other.signingSecret)
                && createdAt.equals(other.createdAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.id,
                this.url,
                this.name,
                this.status,
                this.enabledEvents,
                this.apiVersion,
                this.advancedOptions,
                this.signingSecret,
                this.createdAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>Unique identifier for the webhook endpoint.</p>
         */
        UrlStage id(@NotNull String id);

        Builder from(WebhookEndpointCreate other);
    }

    public interface UrlStage {
        /**
         * <p>The URL that webhook events are sent to.</p>
         */
        NameStage url(@NotNull String url);
    }

    public interface NameStage {
        /**
         * <p>A human-readable name for the webhook endpoint.</p>
         */
        StatusStage name(@NotNull String name);
    }

    public interface StatusStage {
        ApiVersionStage status(@NotNull WebhookEndpointStatus status);
    }

    public interface ApiVersionStage {
        SigningSecretStage apiVersion(@NotNull ApiVersionEnum apiVersion);
    }

    public interface SigningSecretStage {
        /**
         * <p>The signing secret used to verify webhook payloads. This is only returned when creating the endpoint and cannot be retrieved again.</p>
         * <p>Store it securely — you will need it to verify webhook signatures.</p>
         */
        CreatedAtStage signingSecret(@NotNull String signingSecret);
    }

    public interface CreatedAtStage {
        /**
         * <p>The date and time the webhook endpoint was created.</p>
         */
        _FinalStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface _FinalStage {
        WebhookEndpointCreate build();

        /**
         * <p>The list of event types this endpoint is subscribed to at the global level. These are events that are not scoped to a specific resource.</p>
         */
        _FinalStage enabledEvents(List<WebhookEndpointEventType> enabledEvents);

        _FinalStage addEnabledEvents(WebhookEndpointEventType enabledEvents);

        _FinalStage addAllEnabledEvents(List<WebhookEndpointEventType> enabledEvents);

        /**
         * <p>Advanced configuration options for the webhook endpoint, including custom headers and payload delivery settings.</p>
         */
        _FinalStage advancedOptions(Optional<WebhookAdvancedOptions> advancedOptions);

        _FinalStage advancedOptions(WebhookAdvancedOptions advancedOptions);

        _FinalStage advancedOptions(Nullable<WebhookAdvancedOptions> advancedOptions);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IdStage,
                    UrlStage,
                    NameStage,
                    StatusStage,
                    ApiVersionStage,
                    SigningSecretStage,
                    CreatedAtStage,
                    _FinalStage {
        private String id;

        private String url;

        private String name;

        private WebhookEndpointStatus status;

        private ApiVersionEnum apiVersion;

        private String signingSecret;

        private OffsetDateTime createdAt;

        private Optional<WebhookAdvancedOptions> advancedOptions = Optional.empty();

        private List<WebhookEndpointEventType> enabledEvents = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(WebhookEndpointCreate other) {
            id(other.getId());
            url(other.getUrl());
            name(other.getName());
            status(other.getStatus());
            enabledEvents(other.getEnabledEvents());
            apiVersion(other.getApiVersion());
            advancedOptions(other.getAdvancedOptions());
            signingSecret(other.getSigningSecret());
            createdAt(other.getCreatedAt());
            return this;
        }

        /**
         * <p>Unique identifier for the webhook endpoint.</p>
         * <p>Unique identifier for the webhook endpoint.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public UrlStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>The URL that webhook events are sent to.</p>
         * <p>The URL that webhook events are sent to.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("url")
        public NameStage url(@NotNull String url) {
            this.url = Objects.requireNonNull(url, "url must not be null");
            return this;
        }

        /**
         * <p>A human-readable name for the webhook endpoint.</p>
         * <p>A human-readable name for the webhook endpoint.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public StatusStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("status")
        public ApiVersionStage status(@NotNull WebhookEndpointStatus status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("apiVersion")
        public SigningSecretStage apiVersion(@NotNull ApiVersionEnum apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion, "apiVersion must not be null");
            return this;
        }

        /**
         * <p>The signing secret used to verify webhook payloads. This is only returned when creating the endpoint and cannot be retrieved again.</p>
         * <p>Store it securely — you will need it to verify webhook signatures.</p>
         * <p>The signing secret used to verify webhook payloads. This is only returned when creating the endpoint and cannot be retrieved again.</p>
         * <p>Store it securely — you will need it to verify webhook signatures.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("signingSecret")
        public CreatedAtStage signingSecret(@NotNull String signingSecret) {
            this.signingSecret = Objects.requireNonNull(signingSecret, "signingSecret must not be null");
            return this;
        }

        /**
         * <p>The date and time the webhook endpoint was created.</p>
         * <p>The date and time the webhook endpoint was created.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("createdAt")
        public _FinalStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        /**
         * <p>Advanced configuration options for the webhook endpoint, including custom headers and payload delivery settings.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage advancedOptions(Nullable<WebhookAdvancedOptions> advancedOptions) {
            if (advancedOptions.isNull()) {
                this.advancedOptions = null;
            } else if (advancedOptions.isEmpty()) {
                this.advancedOptions = Optional.empty();
            } else {
                this.advancedOptions = Optional.of(advancedOptions.get());
            }
            return this;
        }

        /**
         * <p>Advanced configuration options for the webhook endpoint, including custom headers and payload delivery settings.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage advancedOptions(WebhookAdvancedOptions advancedOptions) {
            this.advancedOptions = Optional.ofNullable(advancedOptions);
            return this;
        }

        /**
         * <p>Advanced configuration options for the webhook endpoint, including custom headers and payload delivery settings.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "advancedOptions", nulls = Nulls.SKIP)
        public _FinalStage advancedOptions(Optional<WebhookAdvancedOptions> advancedOptions) {
            this.advancedOptions = advancedOptions;
            return this;
        }

        /**
         * <p>The list of event types this endpoint is subscribed to at the global level. These are events that are not scoped to a specific resource.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllEnabledEvents(List<WebhookEndpointEventType> enabledEvents) {
            if (enabledEvents != null) {
                this.enabledEvents.addAll(enabledEvents);
            }
            return this;
        }

        /**
         * <p>The list of event types this endpoint is subscribed to at the global level. These are events that are not scoped to a specific resource.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addEnabledEvents(WebhookEndpointEventType enabledEvents) {
            this.enabledEvents.add(enabledEvents);
            return this;
        }

        /**
         * <p>The list of event types this endpoint is subscribed to at the global level. These are events that are not scoped to a specific resource.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "enabledEvents", nulls = Nulls.SKIP)
        public _FinalStage enabledEvents(List<WebhookEndpointEventType> enabledEvents) {
            this.enabledEvents.clear();
            if (enabledEvents != null) {
                this.enabledEvents.addAll(enabledEvents);
            }
            return this;
        }

        @java.lang.Override
        public WebhookEndpointCreate build() {
            return new WebhookEndpointCreate(
                    id,
                    url,
                    name,
                    status,
                    enabledEvents,
                    apiVersion,
                    advancedOptions,
                    signingSecret,
                    createdAt,
                    additionalProperties);
        }
    }
}
