/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum WebhookEventWorkflowRunEventType {
    WORKFLOW_RUN_COMPLETED("workflow_run.completed"),

    WORKFLOW_RUN_FAILED("workflow_run.failed"),

    WORKFLOW_RUN_NEEDS_REVIEW("workflow_run.needs_review"),

    WORKFLOW_RUN_REJECTED("workflow_run.rejected"),

    WORKFLOW_RUN_STEP_RUN_PROCESSED("workflow_run.step_run.processed");

    private final String value;

    WebhookEventWorkflowRunEventType(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
