/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum WorkflowStatus {
    PENDING("PENDING"),

    PROCESSING("PROCESSING"),

    NEEDS_REVIEW("NEEDS_REVIEW"),

    REJECTED("REJECTED"),

    PROCESSED("PROCESSED"),

    FAILED("FAILED");

    private final String value;

    WorkflowStatus(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
