/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.requests;

import ai.extend.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PostFilesRequest.Builder.class)
public final class PostFilesRequest {
    private final String name;

    private final Optional<String> url;

    private final Optional<String> rawText;

    private final Optional<String> mediaType;

    private final Map<String, Object> additionalProperties;

    private PostFilesRequest(
            String name,
            Optional<String> url,
            Optional<String> rawText,
            Optional<String> mediaType,
            Map<String, Object> additionalProperties) {
        this.name = name;
        this.url = url;
        this.rawText = rawText;
        this.mediaType = mediaType;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The name of the file
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return A pre signed URL for the file
     */
    @JsonProperty("url")
    public Optional<String> getUrl() {
        return url;
    }

    /**
     * @return The raw text content of the file
     */
    @JsonProperty("rawText")
    public Optional<String> getRawText() {
        return rawText;
    }

    /**
     * @return The media type of the file (e.g. application/pdf)
     */
    @JsonProperty("mediaType")
    public Optional<String> getMediaType() {
        return mediaType;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PostFilesRequest && equalTo((PostFilesRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PostFilesRequest other) {
        return name.equals(other.name)
                && url.equals(other.url)
                && rawText.equals(other.rawText)
                && mediaType.equals(other.mediaType);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.name, this.url, this.rawText, this.mediaType);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static NameStage builder() {
        return new Builder();
    }

    public interface NameStage {
        /**
         * <p>The name of the file</p>
         */
        _FinalStage name(@NotNull String name);

        Builder from(PostFilesRequest other);
    }

    public interface _FinalStage {
        PostFilesRequest build();

        /**
         * <p>A pre signed URL for the file</p>
         */
        _FinalStage url(Optional<String> url);

        _FinalStage url(String url);

        /**
         * <p>The raw text content of the file</p>
         */
        _FinalStage rawText(Optional<String> rawText);

        _FinalStage rawText(String rawText);

        /**
         * <p>The media type of the file (e.g. application/pdf)</p>
         */
        _FinalStage mediaType(Optional<String> mediaType);

        _FinalStage mediaType(String mediaType);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements NameStage, _FinalStage {
        private String name;

        private Optional<String> mediaType = Optional.empty();

        private Optional<String> rawText = Optional.empty();

        private Optional<String> url = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PostFilesRequest other) {
            name(other.getName());
            url(other.getUrl());
            rawText(other.getRawText());
            mediaType(other.getMediaType());
            return this;
        }

        /**
         * <p>The name of the file</p>
         * <p>The name of the file</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public _FinalStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>The media type of the file (e.g. application/pdf)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage mediaType(String mediaType) {
            this.mediaType = Optional.ofNullable(mediaType);
            return this;
        }

        /**
         * <p>The media type of the file (e.g. application/pdf)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "mediaType", nulls = Nulls.SKIP)
        public _FinalStage mediaType(Optional<String> mediaType) {
            this.mediaType = mediaType;
            return this;
        }

        /**
         * <p>The raw text content of the file</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage rawText(String rawText) {
            this.rawText = Optional.ofNullable(rawText);
            return this;
        }

        /**
         * <p>The raw text content of the file</p>
         */
        @java.lang.Override
        @JsonSetter(value = "rawText", nulls = Nulls.SKIP)
        public _FinalStage rawText(Optional<String> rawText) {
            this.rawText = rawText;
            return this;
        }

        /**
         * <p>A pre signed URL for the file</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage url(String url) {
            this.url = Optional.ofNullable(url);
            return this;
        }

        /**
         * <p>A pre signed URL for the file</p>
         */
        @java.lang.Override
        @JsonSetter(value = "url", nulls = Nulls.SKIP)
        public _FinalStage url(Optional<String> url) {
            this.url = url;
            return this;
        }

        @java.lang.Override
        public PostFilesRequest build() {
            return new PostFilesRequest(name, url, rawText, mediaType, additionalProperties);
        }
    }
}
