/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.resources.processorrun.types;

import ai.extend.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ProcessorRunDeleteResponse.Builder.class)
public final class ProcessorRunDeleteResponse {
    private final boolean success;

    private final String documentProcessorRunId;

    private final String message;

    private final Map<String, Object> additionalProperties;

    private ProcessorRunDeleteResponse(
            boolean success, String documentProcessorRunId, String message, Map<String, Object> additionalProperties) {
        this.success = success;
        this.documentProcessorRunId = documentProcessorRunId;
        this.message = message;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("success")
    public boolean getSuccess() {
        return success;
    }

    /**
     * @return The ID of the deleted processor run
     */
    @JsonProperty("documentProcessorRunId")
    public String getDocumentProcessorRunId() {
        return documentProcessorRunId;
    }

    /**
     * @return Confirmation message
     */
    @JsonProperty("message")
    public String getMessage() {
        return message;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ProcessorRunDeleteResponse && equalTo((ProcessorRunDeleteResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ProcessorRunDeleteResponse other) {
        return success == other.success
                && documentProcessorRunId.equals(other.documentProcessorRunId)
                && message.equals(other.message);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.success, this.documentProcessorRunId, this.message);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static SuccessStage builder() {
        return new Builder();
    }

    public interface SuccessStage {
        DocumentProcessorRunIdStage success(boolean success);

        Builder from(ProcessorRunDeleteResponse other);
    }

    public interface DocumentProcessorRunIdStage {
        /**
         * <p>The ID of the deleted processor run</p>
         */
        MessageStage documentProcessorRunId(@NotNull String documentProcessorRunId);
    }

    public interface MessageStage {
        /**
         * <p>Confirmation message</p>
         */
        _FinalStage message(@NotNull String message);
    }

    public interface _FinalStage {
        ProcessorRunDeleteResponse build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements SuccessStage, DocumentProcessorRunIdStage, MessageStage, _FinalStage {
        private boolean success;

        private String documentProcessorRunId;

        private String message;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ProcessorRunDeleteResponse other) {
            success(other.getSuccess());
            documentProcessorRunId(other.getDocumentProcessorRunId());
            message(other.getMessage());
            return this;
        }

        @java.lang.Override
        @JsonSetter("success")
        public DocumentProcessorRunIdStage success(boolean success) {
            this.success = success;
            return this;
        }

        /**
         * <p>The ID of the deleted processor run</p>
         * <p>The ID of the deleted processor run</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("documentProcessorRunId")
        public MessageStage documentProcessorRunId(@NotNull String documentProcessorRunId) {
            this.documentProcessorRunId =
                    Objects.requireNonNull(documentProcessorRunId, "documentProcessorRunId must not be null");
            return this;
        }

        /**
         * <p>Confirmation message</p>
         * <p>Confirmation message</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("message")
        public _FinalStage message(@NotNull String message) {
            this.message = Objects.requireNonNull(message, "message must not be null");
            return this;
        }

        @java.lang.Override
        public ProcessorRunDeleteResponse build() {
            return new ProcessorRunDeleteResponse(success, documentProcessorRunId, message, additionalProperties);
        }
    }
}
