/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.resources.processorrun.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ProcessorRunListRequestSource {
    ADMIN("ADMIN"),

    BATCH_PROCESSOR_RUN("BATCH_PROCESSOR_RUN"),

    PLAYGROUND("PLAYGROUND"),

    WORKFLOW_CONFIGURATION("WORKFLOW_CONFIGURATION"),

    WORKFLOW_RUN("WORKFLOW_RUN"),

    STUDIO("STUDIO"),

    API("API");

    private final String value;

    ProcessorRunListRequestSource(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
