/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.resources.evaluationsetitems.types;

import ai.extend.core.ObjectMappers;
import ai.extend.types.EvaluationSetItem;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EvaluationSetItemsCreateResponse.Builder.class)
public final class EvaluationSetItemsCreateResponse {
    private final List<EvaluationSetItem> evaluationSetItems;

    private final Map<String, Object> additionalProperties;

    private EvaluationSetItemsCreateResponse(
            List<EvaluationSetItem> evaluationSetItems, Map<String, Object> additionalProperties) {
        this.evaluationSetItems = evaluationSetItems;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("evaluationSetItems")
    public List<EvaluationSetItem> getEvaluationSetItems() {
        return evaluationSetItems;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EvaluationSetItemsCreateResponse && equalTo((EvaluationSetItemsCreateResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EvaluationSetItemsCreateResponse other) {
        return evaluationSetItems.equals(other.evaluationSetItems);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.evaluationSetItems);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<EvaluationSetItem> evaluationSetItems = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(EvaluationSetItemsCreateResponse other) {
            evaluationSetItems(other.getEvaluationSetItems());
            return this;
        }

        @JsonSetter(value = "evaluationSetItems", nulls = Nulls.SKIP)
        public Builder evaluationSetItems(List<EvaluationSetItem> evaluationSetItems) {
            this.evaluationSetItems.clear();
            if (evaluationSetItems != null) {
                this.evaluationSetItems.addAll(evaluationSetItems);
            }
            return this;
        }

        public Builder addEvaluationSetItems(EvaluationSetItem evaluationSetItems) {
            this.evaluationSetItems.add(evaluationSetItems);
            return this;
        }

        public Builder addAllEvaluationSetItems(List<EvaluationSetItem> evaluationSetItems) {
            if (evaluationSetItems != null) {
                this.evaluationSetItems.addAll(evaluationSetItems);
            }
            return this;
        }

        public EvaluationSetItemsCreateResponse build() {
            return new EvaluationSetItemsCreateResponse(evaluationSetItems, additionalProperties);
        }
    }
}
