/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.errors;

import ai.extend.core.ExtendClientApiException;
import ai.extend.types.ApiError;
import okhttp3.Response;

public final class PaymentRequiredError extends ExtendClientApiException {
    /**
     * The body of the response that triggered the exception.
     */
    private final ApiError body;

    public PaymentRequiredError(ApiError body) {
        super("PaymentRequiredError", 402, body);
        this.body = body;
    }

    public PaymentRequiredError(ApiError body, Response rawResponse) {
        super("PaymentRequiredError", 402, body, rawResponse);
        this.body = body;
    }

    /**
     * @return the body
     */
    @java.lang.Override
    public ApiError body() {
        return this.body;
    }
}
