/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.errors;

import ai.extend.core.ExtendClientApiException;
import okhttp3.Response;

public final class TooManyRequestsError extends ExtendClientApiException {
    /**
     * The body of the response that triggered the exception.
     */
    private final Object body;

    public TooManyRequestsError(Object body) {
        super("TooManyRequestsError", 429, body);
        this.body = body;
    }

    public TooManyRequestsError(Object body, Response rawResponse) {
        super("TooManyRequestsError", 429, body, rawResponse);
        this.body = body;
    }

    /**
     * @return the body
     */
    @java.lang.Override
    public Object body() {
        return this.body;
    }
}
