/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.resources.evaluationsetitems;

import ai.extend.core.ClientOptions;
import ai.extend.core.RequestOptions;
import ai.extend.resources.evaluationsetitems.requests.EvaluationSetItemsCreateRequest;
import ai.extend.resources.evaluationsetitems.requests.EvaluationSetItemsListRequest;
import ai.extend.resources.evaluationsetitems.requests.EvaluationSetItemsUpdateRequest;
import ai.extend.resources.evaluationsetitems.types.EvaluationSetItemsCreateResponse;
import ai.extend.resources.evaluationsetitems.types.EvaluationSetItemsDeleteResponse;
import ai.extend.resources.evaluationsetitems.types.EvaluationSetItemsListResponse;
import ai.extend.types.EvaluationSetItem;
import java.util.concurrent.CompletableFuture;

public class AsyncEvaluationSetItemsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawEvaluationSetItemsClient rawClient;

    public AsyncEvaluationSetItemsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawEvaluationSetItemsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawEvaluationSetItemsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * List items in a specific evaluation set.
     * <p>Returns a summary of each evaluation set item. Use the <a href="https://docs.extend.ai/2026-02-09/developers/api-reference/endpoints/evaluation/get-evaluation-set-item">Get Evaluation Set Item</a> endpoint to get the full details of an evaluation set item.</p>
     */
    public CompletableFuture<EvaluationSetItemsListResponse> list(String evaluationSetId) {
        return this.rawClient.list(evaluationSetId).thenApply(response -> response.body());
    }

    /**
     * List items in a specific evaluation set.
     * <p>Returns a summary of each evaluation set item. Use the <a href="https://docs.extend.ai/2026-02-09/developers/api-reference/endpoints/evaluation/get-evaluation-set-item">Get Evaluation Set Item</a> endpoint to get the full details of an evaluation set item.</p>
     */
    public CompletableFuture<EvaluationSetItemsListResponse> list(
            String evaluationSetId, RequestOptions requestOptions) {
        return this.rawClient.list(evaluationSetId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * List items in a specific evaluation set.
     * <p>Returns a summary of each evaluation set item. Use the <a href="https://docs.extend.ai/2026-02-09/developers/api-reference/endpoints/evaluation/get-evaluation-set-item">Get Evaluation Set Item</a> endpoint to get the full details of an evaluation set item.</p>
     */
    public CompletableFuture<EvaluationSetItemsListResponse> list(
            String evaluationSetId, EvaluationSetItemsListRequest request) {
        return this.rawClient.list(evaluationSetId, request).thenApply(response -> response.body());
    }

    /**
     * List items in a specific evaluation set.
     * <p>Returns a summary of each evaluation set item. Use the <a href="https://docs.extend.ai/2026-02-09/developers/api-reference/endpoints/evaluation/get-evaluation-set-item">Get Evaluation Set Item</a> endpoint to get the full details of an evaluation set item.</p>
     */
    public CompletableFuture<EvaluationSetItemsListResponse> list(
            String evaluationSetId, EvaluationSetItemsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(evaluationSetId, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Evaluation set items are the individual files and expected outputs that are used to evaluate the performance of a given extractor, classifier, or splitter in Extend. This endpoint will create new evaluation set items in Extend, which will be used during an evaluation run.
     * <p><strong>Limit:</strong> You can create up to 100 items at a time.</p>
     * <p>Learn more about how to create evaluation set items in the <a href="https://docs.extend.ai/product/evaluation/overview">Evaluation Sets</a> product page.</p>
     */
    public CompletableFuture<EvaluationSetItemsCreateResponse> create(
            String evaluationSetId, EvaluationSetItemsCreateRequest request) {
        return this.rawClient.create(evaluationSetId, request).thenApply(response -> response.body());
    }

    /**
     * Evaluation set items are the individual files and expected outputs that are used to evaluate the performance of a given extractor, classifier, or splitter in Extend. This endpoint will create new evaluation set items in Extend, which will be used during an evaluation run.
     * <p><strong>Limit:</strong> You can create up to 100 items at a time.</p>
     * <p>Learn more about how to create evaluation set items in the <a href="https://docs.extend.ai/product/evaluation/overview">Evaluation Sets</a> product page.</p>
     */
    public CompletableFuture<EvaluationSetItemsCreateResponse> create(
            String evaluationSetId, EvaluationSetItemsCreateRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(evaluationSetId, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Get details of an evaluation set item.
     */
    public CompletableFuture<EvaluationSetItem> retrieve(String evaluationSetId, String itemId) {
        return this.rawClient.retrieve(evaluationSetId, itemId).thenApply(response -> response.body());
    }

    /**
     * Get details of an evaluation set item.
     */
    public CompletableFuture<EvaluationSetItem> retrieve(
            String evaluationSetId, String itemId, RequestOptions requestOptions) {
        return this.rawClient.retrieve(evaluationSetId, itemId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * If you need to change the expected output for a given evaluation set item, you can use this endpoint to update the item. This can be useful if you need to correct an error in the expected output or if the output of the extractor, classifier, or splitter has changed.
     */
    public CompletableFuture<EvaluationSetItem> update(
            String evaluationSetId, String itemId, EvaluationSetItemsUpdateRequest request) {
        return this.rawClient.update(evaluationSetId, itemId, request).thenApply(response -> response.body());
    }

    /**
     * If you need to change the expected output for a given evaluation set item, you can use this endpoint to update the item. This can be useful if you need to correct an error in the expected output or if the output of the extractor, classifier, or splitter has changed.
     */
    public CompletableFuture<EvaluationSetItem> update(
            String evaluationSetId,
            String itemId,
            EvaluationSetItemsUpdateRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .update(evaluationSetId, itemId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Delete an evaluation set item.
     */
    public CompletableFuture<EvaluationSetItemsDeleteResponse> delete(String evaluationSetId, String itemId) {
        return this.rawClient.delete(evaluationSetId, itemId).thenApply(response -> response.body());
    }

    /**
     * Delete an evaluation set item.
     */
    public CompletableFuture<EvaluationSetItemsDeleteResponse> delete(
            String evaluationSetId, String itemId, RequestOptions requestOptions) {
        return this.rawClient.delete(evaluationSetId, itemId, requestOptions).thenApply(response -> response.body());
    }
}
