/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.resources.splitruns.types;

import ai.extend.core.ObjectMappers;
import ai.extend.types.SplitOverrideConfig;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SplitRunsCreateRequestSplitter.Builder.class)
public final class SplitRunsCreateRequestSplitter {
    private final String id;

    private final Optional<String> version;

    private final Optional<SplitOverrideConfig> overrideConfig;

    private final Map<String, Object> additionalProperties;

    private SplitRunsCreateRequestSplitter(
            String id,
            Optional<String> version,
            Optional<SplitOverrideConfig> overrideConfig,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.version = version;
        this.overrideConfig = overrideConfig;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The ID of the splitter to use.
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("version")
    public Optional<String> getVersion() {
        return version;
    }

    /**
     * @return Optional partial configuration override. Only the fields you provide will override the splitter's saved configuration. For example, you can pass only <code>splitRules</code> without providing <code>splitClassifications</code>.
     */
    @JsonProperty("overrideConfig")
    public Optional<SplitOverrideConfig> getOverrideConfig() {
        return overrideConfig;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SplitRunsCreateRequestSplitter && equalTo((SplitRunsCreateRequestSplitter) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SplitRunsCreateRequestSplitter other) {
        return id.equals(other.id) && version.equals(other.version) && overrideConfig.equals(other.overrideConfig);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.version, this.overrideConfig);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>The ID of the splitter to use.</p>
         */
        _FinalStage id(@NotNull String id);

        Builder from(SplitRunsCreateRequestSplitter other);
    }

    public interface _FinalStage {
        SplitRunsCreateRequestSplitter build();

        _FinalStage version(Optional<String> version);

        _FinalStage version(String version);

        /**
         * <p>Optional partial configuration override. Only the fields you provide will override the splitter's saved configuration. For example, you can pass only <code>splitRules</code> without providing <code>splitClassifications</code>.</p>
         */
        _FinalStage overrideConfig(Optional<SplitOverrideConfig> overrideConfig);

        _FinalStage overrideConfig(SplitOverrideConfig overrideConfig);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdStage, _FinalStage {
        private String id;

        private Optional<SplitOverrideConfig> overrideConfig = Optional.empty();

        private Optional<String> version = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(SplitRunsCreateRequestSplitter other) {
            id(other.getId());
            version(other.getVersion());
            overrideConfig(other.getOverrideConfig());
            return this;
        }

        /**
         * <p>The ID of the splitter to use.</p>
         * <p>The ID of the splitter to use.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public _FinalStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>Optional partial configuration override. Only the fields you provide will override the splitter's saved configuration. For example, you can pass only <code>splitRules</code> without providing <code>splitClassifications</code>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage overrideConfig(SplitOverrideConfig overrideConfig) {
            this.overrideConfig = Optional.ofNullable(overrideConfig);
            return this;
        }

        /**
         * <p>Optional partial configuration override. Only the fields you provide will override the splitter's saved configuration. For example, you can pass only <code>splitRules</code> without providing <code>splitClassifications</code>.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "overrideConfig", nulls = Nulls.SKIP)
        public _FinalStage overrideConfig(Optional<SplitOverrideConfig> overrideConfig) {
            this.overrideConfig = overrideConfig;
            return this;
        }

        @java.lang.Override
        public _FinalStage version(String version) {
            this.version = Optional.ofNullable(version);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "version", nulls = Nulls.SKIP)
        public _FinalStage version(Optional<String> version) {
            this.version = version;
            return this;
        }

        @java.lang.Override
        public SplitRunsCreateRequestSplitter build() {
            return new SplitRunsCreateRequestSplitter(id, version, overrideConfig, additionalProperties);
        }
    }
}
