/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.resources.edittemplates;

import ai.extend.core.ClientOptions;
import ai.extend.core.RequestOptions;
import ai.extend.resources.edittemplates.requests.EditTemplatesRetrieveRequest;
import ai.extend.types.EditTemplate;
import java.util.concurrent.CompletableFuture;

public class AsyncEditTemplatesClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawEditTemplatesClient rawClient;

    public AsyncEditTemplatesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawEditTemplatesClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawEditTemplatesClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve a saved edit template by ID.
     * <p>Use this endpoint to inspect the source file, default edit configuration, and optional schema generation configuration saved on an edit template. You can reuse the returned <code>config</code> with <code>POST /edit</code> or <code>POST /edit_runs</code>, and reuse <code>schemaConfig</code> with <code>POST /edit_schemas/generate</code>.</p>
     */
    public CompletableFuture<EditTemplate> retrieve(String id) {
        return this.rawClient.retrieve(id).thenApply(response -> response.body());
    }

    /**
     * Retrieve a saved edit template by ID.
     * <p>Use this endpoint to inspect the source file, default edit configuration, and optional schema generation configuration saved on an edit template. You can reuse the returned <code>config</code> with <code>POST /edit</code> or <code>POST /edit_runs</code>, and reuse <code>schemaConfig</code> with <code>POST /edit_schemas/generate</code>.</p>
     */
    public CompletableFuture<EditTemplate> retrieve(String id, RequestOptions requestOptions) {
        return this.rawClient.retrieve(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieve a saved edit template by ID.
     * <p>Use this endpoint to inspect the source file, default edit configuration, and optional schema generation configuration saved on an edit template. You can reuse the returned <code>config</code> with <code>POST /edit</code> or <code>POST /edit_runs</code>, and reuse <code>schemaConfig</code> with <code>POST /edit_schemas/generate</code>.</p>
     */
    public CompletableFuture<EditTemplate> retrieve(String id, EditTemplatesRetrieveRequest request) {
        return this.rawClient.retrieve(id, request).thenApply(response -> response.body());
    }

    /**
     * Retrieve a saved edit template by ID.
     * <p>Use this endpoint to inspect the source file, default edit configuration, and optional schema generation configuration saved on an edit template. You can reuse the returned <code>config</code> with <code>POST /edit</code> or <code>POST /edit_runs</code>, and reuse <code>schemaConfig</code> with <code>POST /edit_schemas/generate</code>.</p>
     */
    public CompletableFuture<EditTemplate> retrieve(
            String id, EditTemplatesRetrieveRequest request, RequestOptions requestOptions) {
        return this.rawClient.retrieve(id, request, requestOptions).thenApply(response -> response.body());
    }
}
