/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.resources.evaluationset;

import ai.extend.core.ClientOptions;
import ai.extend.core.RequestOptions;
import ai.extend.resources.evaluationset.requests.EvaluationSetCreateRequest;
import ai.extend.resources.evaluationset.requests.EvaluationSetListRequest;
import ai.extend.resources.evaluationset.types.EvaluationSetCreateResponse;
import ai.extend.resources.evaluationset.types.EvaluationSetGetResponse;
import ai.extend.resources.evaluationset.types.EvaluationSetListResponse;
import java.util.concurrent.CompletableFuture;

public class AsyncEvaluationSetClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawEvaluationSetClient rawClient;

    public AsyncEvaluationSetClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawEvaluationSetClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawEvaluationSetClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * List evaluation sets in your account. You can use the <code>processorId</code> parameter to filter evaluation sets by processor.
     * <p>This endpoint returns a paginated response. You can use the <code>nextPageToken</code> to fetch subsequent results.</p>
     */
    public CompletableFuture<EvaluationSetListResponse> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * List evaluation sets in your account. You can use the <code>processorId</code> parameter to filter evaluation sets by processor.
     * <p>This endpoint returns a paginated response. You can use the <code>nextPageToken</code> to fetch subsequent results.</p>
     */
    public CompletableFuture<EvaluationSetListResponse> list(EvaluationSetListRequest request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    /**
     * List evaluation sets in your account. You can use the <code>processorId</code> parameter to filter evaluation sets by processor.
     * <p>This endpoint returns a paginated response. You can use the <code>nextPageToken</code> to fetch subsequent results.</p>
     */
    public CompletableFuture<EvaluationSetListResponse> list(
            EvaluationSetListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Evaluation sets are collections of files and expected outputs that are used to evaluate the performance of a given processor in Extend. This endpoint will create a new evaluation set in Extend, which items can be added to using the <a href="https://docs.extend.ai/2025-04-21/developers/api-reference/evaluation-set-endpoints/create-evaluation-set-item">Create Evaluation Set Item</a> endpoint.
     * <p>Note: it is not necessary to create an evaluation set via API. You can also create an evaluation set via the Extend dashboard and take the ID from there.</p>
     */
    public CompletableFuture<EvaluationSetCreateResponse> create(EvaluationSetCreateRequest request) {
        return this.rawClient.create(request).thenApply(response -> response.body());
    }

    /**
     * Evaluation sets are collections of files and expected outputs that are used to evaluate the performance of a given processor in Extend. This endpoint will create a new evaluation set in Extend, which items can be added to using the <a href="https://docs.extend.ai/2025-04-21/developers/api-reference/evaluation-set-endpoints/create-evaluation-set-item">Create Evaluation Set Item</a> endpoint.
     * <p>Note: it is not necessary to create an evaluation set via API. You can also create an evaluation set via the Extend dashboard and take the ID from there.</p>
     */
    public CompletableFuture<EvaluationSetCreateResponse> create(
            EvaluationSetCreateRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieve a specific evaluation set by ID. This returns an evaluation set object, but does not include the items in the evaluation set. You can use the <a href="https://docs.extend.ai/2025-04-21/developers/api-reference/evaluation-set-endpoints/list-evaluation-set-items">List Evaluation Set Items</a> endpoint to get the items in an evaluation set.
     */
    public CompletableFuture<EvaluationSetGetResponse> get(String id) {
        return this.rawClient.get(id).thenApply(response -> response.body());
    }

    /**
     * Retrieve a specific evaluation set by ID. This returns an evaluation set object, but does not include the items in the evaluation set. You can use the <a href="https://docs.extend.ai/2025-04-21/developers/api-reference/evaluation-set-endpoints/list-evaluation-set-items">List Evaluation Set Items</a> endpoint to get the items in an evaluation set.
     */
    public CompletableFuture<EvaluationSetGetResponse> get(String id, RequestOptions requestOptions) {
        return this.rawClient.get(id, requestOptions).thenApply(response -> response.body());
    }
}
