/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.resources.parserrun.types;

import ai.extend.types.ParserRun;
import ai.extend.types.ParserRunStatus;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;
import java.util.Optional;

public final class ParserRunGetResponseParserRun {
    private final Value value;

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    private ParserRunGetResponseParserRun(Value value) {
        this.value = value;
    }

    public <T> T visit(Visitor<T> visitor) {
        return value.visit(visitor);
    }

    public static ParserRunGetResponseParserRun parserRunStatus(ParserRunStatus value) {
        return new ParserRunGetResponseParserRun(new ParserRunStatusValue(value));
    }

    public static ParserRunGetResponseParserRun parserRun(ParserRun value) {
        return new ParserRunGetResponseParserRun(new ParserRunValue(value));
    }

    public boolean isParserRunStatus() {
        return value instanceof ParserRunStatusValue;
    }

    public boolean isParserRun() {
        return value instanceof ParserRunValue;
    }

    public boolean _isUnknown() {
        return value instanceof _UnknownValue;
    }

    public Optional<ParserRunStatus> getParserRunStatus() {
        if (isParserRunStatus()) {
            return Optional.of(((ParserRunStatusValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<ParserRun> getParserRun() {
        if (isParserRun()) {
            return Optional.of(((ParserRunValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<Object> _getUnknown() {
        if (_isUnknown()) {
            return Optional.of(((_UnknownValue) value).value);
        }
        return Optional.empty();
    }

    @JsonValue
    private Value getValue() {
        return this.value;
    }

    public interface Visitor<T> {
        T visitParserRunStatus(ParserRunStatus parserRunStatus);

        T visitParserRun(ParserRun parserRun);

        T _visitUnknown(Object unknownType);
    }

    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "object", visible = true, defaultImpl = _UnknownValue.class)
    @JsonSubTypes({@JsonSubTypes.Type(ParserRunStatusValue.class), @JsonSubTypes.Type(ParserRunValue.class)})
    @JsonIgnoreProperties(ignoreUnknown = true)
    private interface Value {
        <T> T visit(Visitor<T> visitor);
    }

    @JsonTypeName("parser_run_status")
    @JsonIgnoreProperties("object")
    private static final class ParserRunStatusValue implements Value {
        @JsonUnwrapped
        private ParserRunStatus value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private ParserRunStatusValue() {}

        private ParserRunStatusValue(ParserRunStatus value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitParserRunStatus(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof ParserRunStatusValue && equalTo((ParserRunStatusValue) other);
        }

        private boolean equalTo(ParserRunStatusValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "ParserRunGetResponseParserRun{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("parser_run")
    @JsonIgnoreProperties("object")
    private static final class ParserRunValue implements Value {
        @JsonUnwrapped
        private ParserRun value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private ParserRunValue() {}

        private ParserRunValue(ParserRun value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitParserRun(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof ParserRunValue && equalTo((ParserRunValue) other);
        }

        private boolean equalTo(ParserRunValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "ParserRunGetResponseParserRun{" + "value: " + value + "}";
        }
    }

    @JsonIgnoreProperties("object")
    private static final class _UnknownValue implements Value {
        private String type;

        @JsonValue
        private Object value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private _UnknownValue(@JsonProperty("value") Object value) {}

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor._visitUnknown(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof _UnknownValue && equalTo((_UnknownValue) other);
        }

        private boolean equalTo(_UnknownValue other) {
            return type.equals(other.type) && value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.type, this.value);
        }

        @java.lang.Override
        public String toString() {
            return "ParserRunGetResponseParserRun{" + "type: " + type + ", value: " + value + "}";
        }
    }
}
