/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.resources.classifierversions.types;

import ai.extend.core.ObjectMappers;
import ai.extend.types.ClassifierVersionSummary;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ClassifierVersionsListResponse.Builder.class)
public final class ClassifierVersionsListResponse {
    private final List<ClassifierVersionSummary> data;

    private final Optional<String> nextPageToken;

    private final Map<String, Object> additionalProperties;

    private ClassifierVersionsListResponse(
            List<ClassifierVersionSummary> data,
            Optional<String> nextPageToken,
            Map<String, Object> additionalProperties) {
        this.data = data;
        this.nextPageToken = nextPageToken;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("object")
    public String getObject() {
        return "list";
    }

    @JsonProperty("data")
    public List<ClassifierVersionSummary> getData() {
        return data;
    }

    @JsonProperty("nextPageToken")
    public Optional<String> getNextPageToken() {
        return nextPageToken;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ClassifierVersionsListResponse && equalTo((ClassifierVersionsListResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ClassifierVersionsListResponse other) {
        return data.equals(other.data) && nextPageToken.equals(other.nextPageToken);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.data, this.nextPageToken);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<ClassifierVersionSummary> data = new ArrayList<>();

        private Optional<String> nextPageToken = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ClassifierVersionsListResponse other) {
            data(other.getData());
            nextPageToken(other.getNextPageToken());
            return this;
        }

        @JsonSetter(value = "data", nulls = Nulls.SKIP)
        public Builder data(List<ClassifierVersionSummary> data) {
            this.data.clear();
            if (data != null) {
                this.data.addAll(data);
            }
            return this;
        }

        public Builder addData(ClassifierVersionSummary data) {
            this.data.add(data);
            return this;
        }

        public Builder addAllData(List<ClassifierVersionSummary> data) {
            if (data != null) {
                this.data.addAll(data);
            }
            return this;
        }

        @JsonSetter(value = "nextPageToken", nulls = Nulls.SKIP)
        public Builder nextPageToken(Optional<String> nextPageToken) {
            this.nextPageToken = nextPageToken;
            return this;
        }

        public Builder nextPageToken(String nextPageToken) {
            this.nextPageToken = Optional.ofNullable(nextPageToken);
            return this;
        }

        public ClassifierVersionsListResponse build() {
            return new ClassifierVersionsListResponse(data, nextPageToken, additionalProperties);
        }
    }
}
