/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.resources.evaluationsets;

import ai.extend.core.ClientOptions;
import ai.extend.core.RequestOptions;
import ai.extend.resources.evaluationsets.requests.EvaluationSetsCreateRequest;
import ai.extend.resources.evaluationsets.requests.EvaluationSetsListRequest;
import ai.extend.resources.evaluationsets.types.EvaluationSetsListResponse;
import ai.extend.types.EvaluationSet;
import java.util.concurrent.CompletableFuture;

public class AsyncEvaluationSetsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawEvaluationSetsClient rawClient;

    public AsyncEvaluationSetsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawEvaluationSetsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawEvaluationSetsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * List evaluation sets in your account.
     */
    public CompletableFuture<EvaluationSetsListResponse> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * List evaluation sets in your account.
     */
    public CompletableFuture<EvaluationSetsListResponse> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).thenApply(response -> response.body());
    }

    /**
     * List evaluation sets in your account.
     */
    public CompletableFuture<EvaluationSetsListResponse> list(EvaluationSetsListRequest request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    /**
     * List evaluation sets in your account.
     */
    public CompletableFuture<EvaluationSetsListResponse> list(
            EvaluationSetsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Evaluation sets are collections of files and expected outputs that are used to evaluate the performance of a given extractor, classifier, or splitter. This endpoint will create a new evaluation set, which items can be added to using the <a href="https://docs.extend.ai/2026-02-09/developers/api-reference/endpoints/evaluation/create-evaluation-set-item">Create Evaluation Set Item</a> endpoint.
     * <p>Note: It is not necessary to create an evaluation set via API. You can also create an evaluation set via the Extend dashboard and take the ID from there. To learn more about how to create evaluation sets, see the <a href="https://docs.extend.ai/product/evaluation/overview">Evaluation Sets</a> product page.</p>
     */
    public CompletableFuture<EvaluationSet> create(EvaluationSetsCreateRequest request) {
        return this.rawClient.create(request).thenApply(response -> response.body());
    }

    /**
     * Evaluation sets are collections of files and expected outputs that are used to evaluate the performance of a given extractor, classifier, or splitter. This endpoint will create a new evaluation set, which items can be added to using the <a href="https://docs.extend.ai/2026-02-09/developers/api-reference/endpoints/evaluation/create-evaluation-set-item">Create Evaluation Set Item</a> endpoint.
     * <p>Note: It is not necessary to create an evaluation set via API. You can also create an evaluation set via the Extend dashboard and take the ID from there. To learn more about how to create evaluation sets, see the <a href="https://docs.extend.ai/product/evaluation/overview">Evaluation Sets</a> product page.</p>
     */
    public CompletableFuture<EvaluationSet> create(EvaluationSetsCreateRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieve a specific evaluation set by ID. This returns an evaluation set object, but does not include the items in the evaluation set. You can use the <a href="https://docs.extend.ai/2026-02-09/developers/api-reference/endpoints/evaluation/list-evaluation-set-items">List Evaluation Set Items</a> endpoint to get the items in an evaluation set.
     */
    public CompletableFuture<EvaluationSet> retrieve(String id) {
        return this.rawClient.retrieve(id).thenApply(response -> response.body());
    }

    /**
     * Retrieve a specific evaluation set by ID. This returns an evaluation set object, but does not include the items in the evaluation set. You can use the <a href="https://docs.extend.ai/2026-02-09/developers/api-reference/endpoints/evaluation/list-evaluation-set-items">List Evaluation Set Items</a> endpoint to get the items in an evaluation set.
     */
    public CompletableFuture<EvaluationSet> retrieve(String id, RequestOptions requestOptions) {
        return this.rawClient.retrieve(id, requestOptions).thenApply(response -> response.body());
    }
}
