/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.extend.resources.extractruns.types;

import ai.extend.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ExtractRunsCreateBatchRequestInputsItem.Builder.class)
public final class ExtractRunsCreateBatchRequestInputsItem {
    private final ExtractRunsCreateBatchRequestInputsItemFile file;

    private final Optional<Map<String, Object>> metadata;

    private final Map<String, Object> additionalProperties;

    private ExtractRunsCreateBatchRequestInputsItem(
            ExtractRunsCreateBatchRequestInputsItemFile file,
            Optional<Map<String, Object>> metadata,
            Map<String, Object> additionalProperties) {
        this.file = file;
        this.metadata = metadata;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The file to extract from. Can be a URL, an Extend file ID, or raw text.
     */
    @JsonProperty("file")
    public ExtractRunsCreateBatchRequestInputsItemFile getFile() {
        return file;
    }

    @JsonProperty("metadata")
    public Optional<Map<String, Object>> getMetadata() {
        return metadata;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ExtractRunsCreateBatchRequestInputsItem
                && equalTo((ExtractRunsCreateBatchRequestInputsItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ExtractRunsCreateBatchRequestInputsItem other) {
        return file.equals(other.file) && metadata.equals(other.metadata);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.file, this.metadata);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static FileStage builder() {
        return new Builder();
    }

    public interface FileStage {
        /**
         * <p>The file to extract from. Can be a URL, an Extend file ID, or raw text.</p>
         */
        _FinalStage file(@NotNull ExtractRunsCreateBatchRequestInputsItemFile file);

        Builder from(ExtractRunsCreateBatchRequestInputsItem other);
    }

    public interface _FinalStage {
        ExtractRunsCreateBatchRequestInputsItem build();

        _FinalStage metadata(Optional<Map<String, Object>> metadata);

        _FinalStage metadata(Map<String, Object> metadata);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements FileStage, _FinalStage {
        private ExtractRunsCreateBatchRequestInputsItemFile file;

        private Optional<Map<String, Object>> metadata = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ExtractRunsCreateBatchRequestInputsItem other) {
            file(other.getFile());
            metadata(other.getMetadata());
            return this;
        }

        /**
         * <p>The file to extract from. Can be a URL, an Extend file ID, or raw text.</p>
         * <p>The file to extract from. Can be a URL, an Extend file ID, or raw text.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("file")
        public _FinalStage file(@NotNull ExtractRunsCreateBatchRequestInputsItemFile file) {
            this.file = Objects.requireNonNull(file, "file must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage metadata(Map<String, Object> metadata) {
            this.metadata = Optional.ofNullable(metadata);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "metadata", nulls = Nulls.SKIP)
        public _FinalStage metadata(Optional<Map<String, Object>> metadata) {
            this.metadata = metadata;
            return this;
        }

        @java.lang.Override
        public ExtractRunsCreateBatchRequestInputsItem build() {
            return new ExtractRunsCreateBatchRequestInputsItem(file, metadata, additionalProperties);
        }
    }
}
